<#
.SYNOPSIS
    把 AudioLink 的里程碑 / 任务同步到 GitHub Projects 看板（幂等：重复运行只补齐差异）。

.DESCRIPTION
    内容来源：`docs/05-roadmap.md`（里程碑与退出条件）、`docs/10-handoff.md`（当前进度）。
    **文档仍是唯一事实来源**，本脚本里的任务表只是它的机械映射 —— 改任务请先改文档，再同步这里。

    前置条件（一次性，交互式）：
        gh auth refresh -s project
    token 缺 `project` scope 时脚本会直接给出这条提示并退出。

.EXAMPLE
    pwsh tools/sync-board.ps1 -DryRun      # 只打印将要发生的变更
    pwsh tools/sync-board.ps1              # 真正同步（创建看板 / 字段 / 条目，并回填状态）
#>
[CmdletBinding()]
param(
    [string]$Owner = 'GotKiCry',
    [string]$Repo = 'GotKiCry/AudioLink',
    [string]$ProjectTitle = 'AudioLink 任务看板',
    [switch]$DryRun,
    [switch]$NoLink
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 任务表（docs/05-roadmap.md 的机械映射：M=里程碑，P=优先级，S=状态）
# 优先级含义：P0 = 当前关键路径，P1 = 本里程碑内，P2 = 近期技术债/护栏，P3 = 有余力再做
# ---------------------------------------------------------------------------
$Tasks = @(
    # ---- M0 地基（全部已完成）----
    @{ T = '[M0] CI 能构建内核（core / android / desktop / version-consistency）'; M = 'M0'; P = 'P1'; S = 'Done'; B = '.github/workflows/ci.yml：四 job 并行，单轮约 3–4 分钟' }
    @{ T = '[M0] audiolink-types：协议常量、枚举、错误码、遥测结构'; M = 'M0'; P = 'P1'; S = 'Done'; B = 'docs/03-protocol.md §3/§4.1/§10/§11；serde 为可选 feature（默认零依赖）' }
    @{ T = '[M0] audiolink-proto：ALP/2 编解码 + §12 三组 golden vectors'; M = 'M0'; P = 'P1'; S = 'Done'; B = '数据报 / 控制帧 / 发现报文；L1 严格解码层，非法帧一律 1008 且绝不 panic' }
    @{ T = '[M0] 规格修订：锁定 L1/L2 分层、载荷表、MTU 实测与拒绝矩阵'; M = 'M0'; P = 'P1'; S = 'Done'; B = '§1.1 分层、§3 定长载荷 + QUIC 1162 B 实测、§4 长度约束、§9.2 字段格式、§12 拒绝矩阵' }
    @{ T = '[M0] tools/alp2-dump：协议解码（hex → 人类可读）'; M = 'M0'; P = 'P1'; S = 'Done'; B = '失败时打印 L1 拒绝上下文；结构预筛避免噪声' }
    @{ T = '[M0] tools/latency-probe：QUIC 数据报 RTT / 时钟偏移测量'; M = 'M0'; P = 'P1'; S = 'Done'; B = 'listen/probe；输出 RTT 分位、抖动代理、§6 best8 偏移与极差、§6.5 质量分级' }

    # ---- M1 单链路（关键路径）----
    # 注：标题里的「10–20 ms 缓冲」是当初的规划口径；实测共享模式缓冲下限是 22 ms（1056 帧），
    #     能压到 10 ms 的是引擎周期 —— 为保持看板条目稳定（标题是幂等键），标题不改，口径修正记在 body 与文档里。
    @{ T = '[M1] WASAPI loopback 事件驱动采集（48 kHz / f32 / 2ch，10–20 ms 缓冲）'; M = 'M1'; P = 'P0'; S = 'Done'; B = 'audiolink-audio::wasapi（LoopbackCapture/RenderSink）。实测：缓冲下限 1056 帧=22 ms、引擎周期 10 ms（每周期 480 帧）、空闲端点零数据、COM 对象 !Send 需线程内构造；自环实测零欠载' }
    @{ T = '[M1] Opus 编码（opus-rs，20 ms / 160 kbps / VBR / 48 kHz 锁定）'; M = 'M1'; P = 'P0'; S = 'Done'; B = 'ADR-003：纯 Rust，不装 CMake；实测 encode P50 75 μs / decode 57 μs、160.4 kbps、热路径零分配；已知缺陷：CELT-only 无真 PLC 且 packet_loss_perc 为空设置（见 ADR-003 注记）' }
    @{ T = '[M1] 桌面自环链路 + 四段延迟分解（采集/编码/解码/播放）'; M = 'M1'; P = 'P0'; S = 'Done'; B = 'tools/self-loop：五段分解 + 19 kHz 标记往返实测（同口径模型 7.00 ms vs 实测 6.78 ms）；本机实测合计 39.7 ms，999 帧零欠载零丢弃' }
    @{ T = '[M1] QUIC 通道（quinn：控制流 #0 + 音频数据报）'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'audiolink-net：端点/连接/控制流 #0/时钟估计。实测握手时 max_datagram_size=1162 B，但 DPLPMTUD 会话开始后抬到 1288 B → 发送侧按 min(1200, mds) 封顶（§3 的 1200 B 预算**真的是有效约束**）。未知 OpCode 走 Ok(op=None) 交 L2 忽略计数（§1.1）；peer_cert_der() 供 §5 验签；双向 TLS 让接收侧也能算 peer_id()。19 单测 + 5 真 QUIC 集成测试全绿' }
    @{ T = '[M1] Android 播放（AudioTrack 低延迟模式 + JNI 环缓冲 + 欠载检测）'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'LowLatencyPlayer（PERFORMANCE_MODE_LOW_LATENCY + WRITE_NON_BLOCKING + USAGE_MEDIA + 48k/2ch/FLOAT，播放线程内 build/write/release，§1 第 3 条未反转）+ 纯逻辑播放环 + 欠载/溢出计数；assembleDebug 与 testDebugUnitTest 通过（31 个 JVM 用例）。⚠️ **真机指标全部未验证**（本机 adb 无设备、无可用 AVD）：getPerformanceMode() 实测值、出声延迟、30 min 无断流。顺带修掉一个 minSdk 26 上调用 API 29+ 三参 startForeground 的既有崩溃缺陷' }
    @{ T = '[M1] 最小 UI（桌面手工 IP 连接；Android 服务启停）'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'FR-29 / FR-35 的最小形态。桌面：手工 IP → 连接 → 对端卡片（名字/短指纹/状态/是否受信）→ 开始·停止推流 → 遥测数字面板 → PIN 输入框；外壳已**接真实引擎**（无 mock），含一个起两个真 Engine 的接缝测试（真 QUIC + 真配对）。Android：服务启停 + 状态卡片（低延迟是否生效 / 采样率 / 缓冲帧数 / 欠载）。⚠️ **UI 交互与视觉未验证**（无头环境点不了，应用从未启动过）' }
    @{ T = '[M1] PIN 配对最小可用（白名单落盘）'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'audiolink-identity：自签证书（SAN 固定 "audiolink"，展示名不进证书 → 改名不换身份）+ SHA-256 指纹 + ECDSA-P256 挑战应答 + 信任库原子落盘（损坏必须 Err，绝不静默重置）+ PinGate（6 位 / 60 s / 5 次锁 5 分钟 / 成功后不可重放）。30 测试全绿。已在 link-loop 里跑通真实 PIN 配对（node-b 显示 308011 → node-a 提交 → 双方落盘）' }
    @{ T = '[M1] 引擎编排：会话状态机 + 收发管线 + 遥测聚合'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'audiolink-engine：§4 控制帧载荷（postcard）+ L2 分发层（未知/未实现/载荷非法三分支分别计数，一律不断流）+ 会话状态机（非法迁移显式报错，Failed 可重启）+ 采集线程（拥有 !Send 的 CaptureSource）→ 编码 → 数据报 + 数据报 → 解码 → 时钟驱动播放线程 + 1 Hz 遥测。60 测试全绿' }
    @{ T = '[M1] 验收：P50 ≤ 110 ms / P95 ≤ 150 ms、零重采样、低延迟模式生效'; M = 'M1'; P = 'P1'; S = 'In Progress'; B = '2026-09-16 更新：PHK110 / Android 16 新包已安装并回拉核对；LOW_LATENCY、48 kHz / 2ch、PCM_FLOAT 与 FAST 路径生效，PIN 与服务生命周期验收通过。待播队列增长已修复：180 s P50/P95/max 从 240/300/320 ms 降至 40/40/60 ms，首尾 40→40 ms；手机 PCM 环约 105 s 无新增溢出、读空、系统欠载或写错。当前已有段模型 e2e 下限约 73 ms，但对端解码、AudioTrack 输出及声学端到端 P50/P95 尚未完整测量；修复后 30 min 长跑也未执行，因此保持 In Progress。迟到丢弃 143 次转由 M2 自适应抖动缓冲/PLC 优化。详见 docs/16-android-service-lifecycle.md；历史 MI 8 Lite 验收见 docs/12-m1-device-acceptance.md。' }
    @{ T = '[工具] link-loop：PC↔PC 真 QUIC 端到端验收'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'tools/link-loop：同进程起两个真实 Engine，走真实 QUIC（TLS + 证书指纹互认 + §5 握手 + PIN 配对），用共享 MeasurementTap 按 seq 配对量「帧封口→sink 写出」。与 self-loop 的分工：self-loop 量单进程音频链，link-loop 量含网络与会话的完整链路' }
    @{ T = '[质量] 端到端延迟回归护栏（回环 P50/P95 进集成测试）'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-17 完成。M1 的验收线（P50 ≤ 110 ms / P95 ≤ 150 ms）此前只有**人工**测量 —— tools/link-loop 跑一次、人眼看数字；问题不在测量本身，而在于人工测量不会在回归时报警：某次改动让延迟翻倍，要等下次有人想起来跑一遍才会发现。新增 core/crates/audiolink-engine/tests/engine/latency_budget.rs：两个真实 Engine（真 QUIC + PIN 配对）+ 合成源 + NullPlayout，两端装同一个 MeasurementTap（发送侧记「帧封口」、接收侧记「sink 写出」，按 seq 配对）—— 量法与 link-loop 完全同一套，不另写一份。实测基线（本机，且 8 h 长跑同时在跑）：P50 = 40 615 µs、P95 = 41 007 µs、P99 = 41 132 µs，约等于两帧（20 ms 编码 + 20 ms 抖动缓冲），与项目历史记录（40.28/40.73 ms）一致。阈值取实测的 2–3.7 倍（P50 ≤ 80 ms、P95 ≤ 150 ms）—— 按「实测 × 倍数」定而不是按验收线定：宁可漏报一次轻微退化，也不要让 CI 因共享 runner 抖动随机变红，因为一条会随机变红的护栏很快会被学会忽略。**边界写清了**：回环没有 Wi-Fi 抖动与扬声器缓冲，这个数字不能用来宣称 M1 验收通过，它只回答「延迟有没有突然变坏」；真机延迟仍在人工验收清单里。验证：engine 167 项全过（含本项）、fmt / clippy 零警告；测试会把量到的 P50/P95/P99 与配对帧数打印出来，CI 日志里直接可读。详见 docs/47-m1-latency-guard.md。' }
    @{ T = '[M1] 真机验收：Android 低延迟/出声延迟/30 min 无断流'; M = 'M1'; P = 'P1'; S = 'In Progress'; B = '2026-09-16 PHK110 / API 36：最新双 ABI Release 已安装、V2 签名及回拉 SHA-256 一致；LOW_LATENCY、48 kHz / 2ch、PCM_FLOAT 与 FAST 生效，PIN、6 轮普通启停、3 轮四连点、推流中和配对中重启通过。待播队列修复后 180 s 全程 streaming，P50/P95/max 40/40/60 ms、首尾均 40 ms，链路丢包 0%；手机 PCM 环约 105 s 无新增溢出/读空/系统欠载/写错。仍缺修复后 30 min 长跑和声学出声延迟 P50/P95，保持 In Progress。详见 docs/16-android-service-lifecycle.md；历史 MI 8 Lite 结果见 docs/12-m1-device-acceptance.md。' }
    @{ T = '[M1] 桌面外壳接入真实 engine（替换 mock）'; M = 'M1'; P = 'P1'; S = 'Done'; B = 'MockEngine / run_mock_source 已整块删除，engine_bridge.rs 现为真实实现（Engine::start + spawn_accept_loop + subscribe → 三事件翻译 + 状态映射 + 遥测聚合）。**含一个起两个真 Engine 的运行时接缝测试**（真 QUIC + 真 PIN 配对，断言 connect 返回 1002 但对端已进 peers()、submit_pin 结果走事件回来、start_send 后接收端出现非零码率）。⚠️ 真实 WASAPI 采集/播放工厂按签名写好但**未启动过应用**（会真采集真放音）；UI 交互与视觉未验证' }
    @{ T = '[M1] Android 接入 FFI 绑定（JNA + 播放环适配 + 引擎随服务启停）'; M = 'M1'; P = 'P1'; S = 'Done'; B = '绑定源集**挂载而非复制**（../core/crates/audiolink-ffi/bindings/kotlin，保证绑定与 .so 永远同源）+ jna 5.19.1@aar；FfiPcmFeed 把 PcmFeed → PcmRingBuffer（环满时把 accepted<frames 上报给内核遥测）；engineStart/engineStop 跟随服务生命周期（listenPort=0 用内核默认端口，不在 Kotlin 侧硬编码）；catch(Throwable) 接住 JNA 的 UnsatisfiedLinkError 以免服务进程崩。验收：assembleDebug + testDebugUnitTest **38/38** + lintDebug 0 error，APK 22.7 MB。⚠️ JNA 运行期加载 .so、端到端 PCM 链路、GC 抖动均**未验证**（无真机）' }

    # ---- 本轮（M1 真机验收）新增与重写 ----
    @{ T = '[M1] §6 时钟同步接线进引擎（CLOCK_PROBE/REPLY + ClockEstimator + 对端遥测）'; M = 'M1'; P = 'P0'; S = 'Done'; B = 'audiolink-engine::clock：响应方立即回 CLOCK_REPLY（不依赖 §5 会话状态，latency-probe 这类裸测量客户端也能用）、发起方 100ms×50→1Hz 探测、估计写遥测；新增 clock_estimate()/peer_stats()/clock_probe_stats()（含逐探针 RTT 环 P50/P95）。真机实测 60/60 样本（旧内核 0 样本）、收敛 1.01 s、|offset| 38 µs（同进程真值 0）' }
    @{ T = '[M1] tools/device-link：PC 侧真机验收（连接 / PIN / 推流 / 跨机账本 / JSON）'; M = 'M1'; P = 'P0'; S = 'Done'; B = '真实 Engine + 真实 QUIC + §5 配对 + 可选真实 WASAPI loopback 采集；账本逐项标 [实测]/[模型]/[未测] 并给未测项清单；--pin-file 支持无头投喂（内核每连接新建 PinGate，必须同连接内提交）；--self-test 同进程双 Engine 自检；退出码 0/2/3/4/5 分门别类。真机实测四轮 60/60/90/75 s 推流零断流' }
    @{ T = '[M1] Android UI 显示配对 PIN + 对端列表'; M = 'M1'; P = 'P0'; S = 'Done'; B = '真机验收暴露的真缺口：FFI 早已导出 displayedPin()，但 Kotlin 从未调用 → 手机从不显示 PIN，§5 配对在 Android 侧根本走不通。已修（56sp 大字卡片 + 对端名/短指纹/受信/状态），真机验证；新增 17 个 JVM 用例' }
    @{ T = '[M1] 修复配对死线：握手 10 s < PIN 有效期 60 s（人工配对必然失败）'; M = 'M1'; P = 'P0'; S = 'Done'; B = '真机首跑报 1002 NOT_PAIRED（unknown peer）：握手死线 10 s 到点回收会话，而 §5 的 PIN 有效期 60 s。改为配对等待不吃死线（默认 10 s / 75 s 窗口，权威判据仍在 PinGate）；含负向对照（arm_pin_wait 改空操作 → 用例立刻变红）；真机延迟 ≥25 s 提交 PIN 配对通过' }
    @{ T = '[M1] Android 播放队列水位控制 + 设备侧缓冲 A/B'; M = 'M1'; P = 'P1'; S = 'Done'; B = '同连接内 A/B：满灌 101 ms / 队列目标 30 ms→51 ms（零欠载代价）/ 容量收缩 960r→41 ms，全部保住 FAST。结论：设备侧省的 50–66 ms 被上游推送速率吃掉（见下一条）。默认保持满灌，档位留 UI chip（改一行常量即可启用）' }
    @{ T = '[M1→M2] 内核→Kotlin PCM 推送 ≈ 2× 实时（环持续溢出 48.6k 帧/s）'; M = 'M1'; P = 'P0'; S = 'Done'; B = '2026-09-16：Issue #1 的代码修复已完成，用户已确认新 APK 音频正常传输和播放，Issue #1 已关闭。receive_audio 把封装已返回的交错样本数再次乘 2，导致等长静音尾部；现直接截取有效长度，解码缓冲收缩为单包。新增真实 Engine→QUIC→Opus→sink 回归：20 ms=1920 样本、10 ms=960 样本，旧代码均失败、修复后通过；fmt/clippy/内核完整测试通过。本机 60 s 推流欠载/迟到/PLC=0，队列末值40 ms，帧封口→sink P50/P95=40.28/40.73 ms；不能替代手机端到端验收。该修复标为 Done；长时间队列稳定性与端到端延迟仍由独立验收项追踪。buffer_level_us 已明确只含引擎待播队列，不含 Kotlin 环/AudioTrack。历史真机：78 s 环溢出 +3 791 040 帧、读空 +0。复测步骤见 docs/12-m1-device-acceptance.md §9。https://github.com/GotKiCry/AudioLink/issues/1' }
    @{ T = '[M1] 真机验收报告 + 独立复核（41 项三态判定）'; M = 'M1'; P = 'P0'; S = 'Done'; B = 'docs/12-m1-device-acceptance.md：设备侧两项硬指标达标（LOW_LATENCY / 48 kHz 零重采样）、四轮零断流；e2e 延迟未达标（下限 ≥115 ms + 设备输出 80–101 ms）；独立验证者复核 41 项 → 可信 29 / 存疑 8 / 不成立 4，4 项已修正并留痕（含 run4 欠载被写成更漂亮的值）' }

    # ---- 2026-09-15 深夜：发行构建 + 真机联调新发现 ----
    @{ T = '[M1] 发行构建：release APK 首次打通（签名 keystore + R8 规则 + gitignore 修口）'; M = 'M1'; P = 'P1'; S = 'Done'; B = '此前 release 路径从未跑过：proguard-rules.pro 根本不存在（R8 会把 JNA/UniFFI 反射目标删掉）。已补 JNA/UniFFI keep 规则 + 生成 release keystore（RSA4096/30 年）+ .gitignore 加 android/keystore.properties（实测原本没被忽略，PUBLIC 仓库存在口令入库风险）。产物 app-release.apk 7.98 MB 已签名（V2）。⚠️ MIUI 上 adb install 报 -99（需开发者选项「USB 安装」）' }
    @{ T = '[M1 听感缺陷] 接收侧待播队列持续增长，触顶后丢帧'; M = 'M1'; P = 'P0'; S = 'Done'; B = '2026-09-16 已修复并完成 PHK110 / API 36 真机复测。根因是欠载补静音或播放线程跨过时钟拍后没有推进音频序号，迟到旧帧仍在下一拍播放，短暂停顿会永久增加队列延迟。现以 expected_seq 作为播放时钟游标：静音和错过的拍也推进，迟到帧丢弃，未来帧保留，并支持 u32 回绕。真实 QUIC/Opus 回归注入 250 ms sink 停顿：旧代码恢复后 P50 271 ms，修复后连续 5 次 P95 20.6–40.7 ms。手机 180 s 队列从修复前 P50/P95/max 240/300/320 ms、首尾 40→300 ms，降至 40/40/60 ms、首尾 40→40 ms；链路丢包 0%，设备播放环约 105 s 内无新增溢出/读空/系统欠载/写错。欠载/迟到 0→143 是主动丢弃过期帧的明确账本，减少该计数转入 M2 自适应抖动缓冲与 PLC；M1 总延迟仍独立验收。Rust fmt/Clippy/全测试通过；详见 docs/16-android-service-lifecycle.md。' }
    @{ T = '[M1] 桌面 UI 缺采集端点选择器（只能吃默认输出端点）'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-16：实现完成。新增真实 WASAPI 输出端点下拉、刷新、格式与不可用原因、虚拟设备提示、实际采集端点展示和启动日志；完整 ID 精确选择，缺失端点不回退默认。推流期间先停止再切换。Engine::start_send 现等待本地采集/编码初始化并回传失败，支持同连接重试、拒绝重复开流。完整内核/桌面测试与 Clippy 通过；本机 4 个真实端点选择 ID 与实际打开 ID 一致，缺失 ID 拒绝；Tauri 窗口验证选择与刷新，1100×720/880×560/深色截图通过。测试版 target/x86_64-pc-windows-msvc/debug/audiolink-desktop.exe；说明 docs/13-desktop-capture-selection.md。' }
    @{ T = '[M1] Android PIN 卡有时不显示（已进入配对分支但屏幕无 PIN 卡）'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-16：完成。Engine 同步快照修复已通过自动回归；PHK110 / Android 16 / API 36 真机验证屏幕 PIN、错一次后保留、成功清除、未配对断开清除、同身份重连、60 s 到期、五次输错关闭连接，以及配对中停止/重启。UI XML、截图与真实 QUIC 客户端日志共同核对；新包安装后回拉比对 SHA-256 一致。Android 全部 73 项 JVM 测试通过，详见 docs/14-pairing-state.md、docs/16-android-service-lifecycle.md。当前 Release：android/app/build/phk110-validation/outputs/apk/release/app-release.apk。' }
    @{ T = '[M1] 引擎停止后立即重启：QUIC 端口尚未释放'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-16：已修复。原 PIN 回归恢复同端口可稳定复现 Windows 10048，修复后通过。Engine 禁止新任务并等待接受/主动连接/会话及音频线程退出；net 等待真实 UDP 套接字及 IO poller 释放通知；FFI 启停串行，同配置幂等、不同配置 BUSY。等待锁时取消不执行，派发后取消等待仍完成操作。新增 5 项回归覆盖 15 次五状态同端口重启（空闲/等 PIN/已连接/接收/发送）、并发冷启动与重复停止、播放回调阻塞后取消停止再重启、未完成 QUIC 握手、socket/poller 持有与取消恢复。fmt、Clippy 与内核/桌面测试通过；双 ABI Debug/Release APK 构建并核对内核，Release V2 签名通过；未改动的 Kotlin 69 项 JVM 测试使用缓存通过。新 Release：android/app/build/restart-validation/outputs/apk/release/app-release.apk。详见 docs/15-engine-restart.md；本轮 ADB 无设备，手机界面复测仍留在真机验收项。' }
    @{ T = '[M1] Android 停止服务后旧协程回写运行中，无法再次启动'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-16：已修复并完成 PHK110 / Android 16 真机验收。旧 Service 销毁后 stopEngine 协程会回写运行中，导致按钮无法再次启动；现用进程级请求队列保证旧停止先于新启动，按实例代次丢弃旧启动/PIN 查询结果，仅主线程发布 UI。新增 4 项生命周期回归，Android 73 项 JVM 测试、Debug/Release 构建、Release V2 签名及 Rust fmt/Clippy/内核测试通过。手机 6 轮普通启停、3 轮四连点、推流中与配对中重启通过；安装包回拉 SHA-256 与本地一致。产物 android/app/build/phk110-validation/outputs/apk/release/app-release.apk；详见 docs/16-android-service-lifecycle.md。' }

    @{ T = '[M1 工具] 延迟探针并发写入丢失时间戳配对'; M = 'M1'; P = 'P1'; S = 'Done'; B = '2026-09-16：已修复 MeasurementTap 并发竞态。CI 35056343048 的既有并发回归只配对 1992/2000；逐序号同步起跑强化后旧代码为 645/2000。现由同一状态锁原子完成查找、配对、留存、样本更新与清空，修复后配对 2000/2000、孤儿零、全部延迟 25 ms；测量模块 8 项测试、Rust fmt、全内核 Clippy 与测试通过。保持有界窗口及公开 API；Android 默认音频路径未启用此探针，接收队列增长仍独立跟踪。详见 docs/16-android-service-lifecycle.md 的 CI 后续记录。' }
    @{ T = '[环境] MIUI 上 adb install release APK 失败 -99（需「USB 安装」权限）'; M = 'M1'; P = 'P2'; S = 'Todo'; B = 'debug 包可装（debuggable），release 包在 MIUI 上被拒：Failure [-99]。需在开发者选项打开「USB 安装」（可能要求登录小米账号）。属环境/文档项，代码侧无问题（APK 签名校验通过、清单 minSdk26/targetSdk36 正常）' }
    # ---- M2–M5 ----
    @{ T = '[M2] 稳定性与质量：抖动缓冲 + 双发/PLC/NACK + 自适应码率 + 遥测面板'; M = 'M2'; P = 'P2'; S = 'In Progress'; B = 'docs/05-roadmap.md M2；验收含 8 h soak 与弱网（5 Mbps / 2% 丢包 / 30 ms 抖动）。2026-09-16：播放游标、PCM 丢包掩盖、自适应抖动/有界重排和默认冗余双发已完成。副本延迟一帧，接收按序号去重且质量指标只取首个有效副本；最高 60 ms 档欠载可同档补水。PC 双 Engine 与 PHK110 真实 QUIC 码率均稳定 320.8 kbps；手机 90 s 队列 P50/P95/max 60 ms，链路丢包/PLC 0，欠载/迟到 24/22 且第 75–90 s 无新增，AudioTrack underrun 0、FastMixer writeErrors 0。NACK 重传、soak-runner、自适应码率与弱网测试台均已落地（docs/21、docs/22、docs/23、docs/24）。M2 弱网口径已实测通过（60 s：2% 丢包 / 15±15 ms / 5 Mbps → exit 0、掩盖 0.13%、全程 streaming）。2026-09-16 遥测面板（5 分钟曲线 + CSV 日志导出）已完成（提交 87cb059 / CI 35079292910 / docs/25）。下一步只剩：**真正跑一次 8 h soak**（工具就绪）、真机弱网与更高丢包档（触发降级）；单声道降级与帧长 10 ms 切换已在 LinkSeverity 记账、留待专门任务。详见 docs/17-m2-pcm-concealment.md、docs/18-m2-adaptive-jitter.md、docs/19-m2-redundant-send.md。2026-09-16：8 h 弱网长跑（2% 丢包 / 15±15 ms / 5 Mbps，--tolerant 判据）已在后台启动，目标 28800 s，报告与注入自账落到 target/evidence/soak/soak-8h-netem.json（+ .netem.json）。长跑期间本机同时有开发编译与测试活动，结论出来时会把这一点一起记下来（不粉饰）。（28800 s，tolerant 档，采样 28798 次）：掩盖率 0.066%（弱网门槛 1%）、注入自账 2.01%、末次漂移 -4 ppm、RTT 41.8 ms、水位 120 ms。长跑逼出并修掉弱网档三个判定缺陷（码率判据未关、0 = 不判 语义与实现相反、快照总量配额被单类独占），详见 weak-network 条目与 docs/22 §9。本项仍为 In Progress：修完判据后需要重跑一次 8 h 才算完成，且真机（PC→Android）长跑验收与 M1 真机延迟项仍待做。 2026-09-17 M2 的 8 h 弱网长跑已执行' }
    @{ T = '[M2] 自适应抖动缓冲（20–60 ms）+ 有界乱序重排'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。接收侧以 1 Hz 到达抖动 P95 和新增欠载驱动 20/40/60 ms 三档目标：升档立即，连续稳定 30 s 后逐档下降；播放线程按实际水位缺口执行最多 60 ms 的有界重缓冲，降档只丢真实多余深度，且原子发布不会覆盖并发欠载升档。仅 60 ms 档允许等待一帧修复乱序，待排序包上限 3；超时转 PCM 掩盖，覆盖重复、迟到、回绕和大跳变。后续双发真机回归补齐最高档欠载后的同档补水：队列重新出现数据才建立余量，完全断流时继续推进时间轴。真实 Opus、250 ms sink 停顿和 PHK110 90 s 回归通过；最终手机队列 P50/P95/max 60 ms，欠载/迟到 24/22 且第 75–90 s 无新增，AudioTrack underrun 0。真实 2%/30 ms 弱网及 8 h soak 留在 M2 父任务。详见 docs/18-m2-adaptive-jitter.md、docs/19-m2-redundant-send.md。' }
    @{ T = '[M2] 默认冗余双发（延迟一帧副本 + 接收去重）'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。发送当前主包后再发上一帧副本，同序号副本间隔至少一个 20 ms 包时距；副本保持 AUDIO 并标记 FEC_REDUNDANT。接收乱序窗按近期已交付和待排序序号静默去重，主/副本谁先到采用谁；丢包分母、PLC、迟到与 jitter 只按唯一序号，链路码率按两个数据报。真实 Opus 注入丢主包验证副本恢复且 0 loss/PLC/late；PC 双 Engine 20 s 码率 320.8 kbps、零欠载/迟到。PHK110 90 s 码率末值/均值 320.8 kbps，链路丢包/PLC 0，队列 P50/P95/max 60 ms，欠载/迟到 24/22 且第 75–90 s 无新增；APK SHA-256 4ef38c519454ba427ae69aa6c9341ea5665c5b97454da31e09dafb05f9e66140。下一步 NACK；真实弱网仍在 M2 父任务。详见 docs/19-m2-redundant-send.md。' }
    @{ T = '[M2] 自建丢包掩盖（CELT-only 无真 PLC：重复上一包 + 淡出 + 交叉淡化）'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。新增 PcmConcealer：重复上一帧、120 ms 线性淡出、恢复时 2.5 ms 交叉淡化；AudioReceiver 将 Opus、掩盖历史与序号统一推进，迟到包解码前丢弃，解码失败同样掩盖，长空洞最多补 120 ms 并重建解码器，避免塞满播放队列。opus-rs 无逐包模式 getter，所有档位保守跳过未经证明的原生 conceal；实测连续调用原生 conceal 会把 6 帧丢包后的恢复 RMS 压到约 0.002。真实 Opus 回归覆盖约 2% 确定性丢包（4/201，无序号洞且掩盖 RMS > 0.02）、120 ms 突发、u32 回绕、解码失败、迟到包和 999 帧空洞。PHK110 正常链路 60 s 队列 P50/P95/max 40/40/40 ms、链路丢包/PLC 0，APK SHA-256 b51180b4bb208ae273d4eb2bccb66e6728375fbafffa219c31dd13b2b05da2e7；真实网络 2%/30 ms 弱网仍属 M2 父任务。详见 docs/17-m2-pcm-concealment.md。' }
    @{ T = '[M2] NACK 重传（洞检测 + 1 s 重传窗口 + 有界等重传）'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。新增 audiolink-engine::runtime::nack：接收侧 MissingTracker 从序号洞里认出缺哪几帧（最旧的洞先请求、重试 ≤ 5 次、间隔 10 ms、窗口 1 s、跳变 ≥ 1000 帧按时间轴重建、同时跟踪 ≤ 64 个洞并计 overflow、序号回绕按半程判据），按 §3 的 16 项上限组 NACK；仅 QUIC 平滑 RTT < 30 ms 时发送，每次发一条记一次 nack_count。发送侧 RetransmitBuffer 保留最近 1 s 已发出的帧（同序号只留一份、容量 128 帧），收到 NACK 逐序号重发，序号与 sample_index 原样保留、且不计入发送侧 expected/received 分母（否则丢包率会被自己的重传擦干净）。关键改动：PacketReorderBuffer 新增 set_retransmit_grace —— 有洞且播放队列深度 ≥ 2 帧时才给有界等待 min(2×RTT+5 ms, 30 ms)，到点由 flush_expired 按原策略交付；无洞链路零额外延迟。验证：nack 单测 11 项 + jitter 等重传窗口 4 项 + 端到端 1 项（真实双 Engine + QUIC + 有损 UDP 中继，每 10 个大包丢连续 2 个 ≈ 20%）：接收侧 nack_count=16、plc_count=0（解码序列一个洞都没有）；破坏性对照 NACK_MAX_RTT_US=0 → nack_count=0、plc_count=16（= 丢包数）。已知取舍：每次重传仍伴随一次播放欠载（≈20 ms 静音，等重传期间播放队列只出不进），听感收益的最后一公里需与抖动缓冲联动，留 M2 后续。提交 2eaff74；CI run 35071772598（core / android / desktop / version-consistency）全绿。详见 docs/21-m2-nack-retransmit.md。' }
    @{ T = '[M2] 自适应码率（丢包驱动升降级 + 遥测时间线）'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。新增 audiolink-engine::adaptive（纯状态机，8 项单测）：丢包 > 1% 持续 3 s → 码率 −20%（下限 96 kbps，降完重新攒窗口，故持续丢包是每 3 s 一级）；连续 10 s 无丢包且 RTT ≤ 30 ms → +10%（上限 320 kbps），每 5 s 最多一级；初值夹到 96..=320 kbps。发送侧接线：1 Hz ticker 用**对端** STREAM_STATS 的 loss_pct_x100 / rtt_us 判定（丢包只有接收侧看得见），结果写进采集线程共享的 Arc<AtomicI32>，采集线程每帧前 load，变化即 encoder.set_bitrate（opus-rs 的 bitrate_bps 每帧读取，下一帧生效、不重建编码器）；变更通过新增 EngineEvent::CodecAdapted{from_bps,to_bps,reason} 形成验收时间线（桌面侧已同步处理该变体，目前只记日志）。端到端（真实双 Engine + QUIC，从码率下限起步）：事件 [(96000→105600), (105600→116160)]，接收侧链路码率 192.8→233.2 kbps（双发两倍）—— 决策真的落到线上。破坏性对照：去掉写新码率给采集线程 → 事件照发但线上码率不变（192800→192800），测试变红。未做（已记账、不假装）：立体声→单声道（要动 format::CHANNELS）、帧长 20→10 ms（OPEN_STREAM 已协商参数）、遥测面板曲线、真实弱网下的降级实测。重要发现：回环上「降级」不可复现 —— 40% 人为丢包被双发 + NACK 全部修复，接收侧丢包率恒为 0，而「修好了就不该降码率」是正确行为。提交 f66a551；CI run 35074883157（core / android / desktop / version-consistency）全绿。详见 docs/23-m2-adaptive-bitrate.md。' }
    @{ T = '[M2] 弱网测试台 netem-sim + 弱网长跑验收'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成（路线图 M2 交付物 6）。新增 audiolink-tools::netem：确定性注入内核（xorshift64* 同种子可复现；按概率丢包、令牌桶限速、固定延迟 ± 抖动；只丢不改）7 项单测；NetemRelay 透明 UDP 中继（按来源地址区分客户端/上游，QUIC 端到端加密故只搬字节）。新增 --bin netem-sim（独立工具，打印监听地址供发起方连接，结束写 JSON 自账）。soak-runner 集成 --netem-*（两个 Engine 之间自动插中继，长跑与注入一条命令）与 --tolerant 弱网档（只钉会话不断 + 掩盖比例 ≤ 1%，不判欠载/迟到/NACK/瞬时丢包 —— 瞬时 loss 在 2% 注入下会跳到 2-4% 而窗口平均掩盖仅 0.13%，拿它当门槛只会假警报）。实测 M2 弱网口径 60 s（2% 丢包 / 15±15 ms / 5 Mbps）：全程 streaming、接收侧丢包 0、掩盖 4 帧（0.13%）、欠载 10、迟到 12、NACK 0、RTT≈41 ms → 判定 ok / exit 0；注入自账 观察 5676 / 转发 5571 / 丢 105（1.85%）。顺带修真实缺陷：SoakThresholds 的四个 max_* 字段此前定义了却未被判定逻辑使用（现在 check_delta 真按「累计值超过阈值的增量」判，默认 0 时行为不变）。结论：弱网下不该降码率（链路被修复=链路没坏），触发降级需更高丢包档，记为后续。提交 556e504；CI run 35077260006（core / android / desktop / version-consistency）全绿。详见 docs/24-m2-netem-sim.md。（28800 s / 5 Mbps / 2% 丢包 / 15±15 ms，tolerant 档，采样 28798 次、粗采样 481 桶）实跑完成。判定 failed 但根因不在链路 —— 7055 条异常全部是同一类 bitrate_out_of_range（集中在 2692..8293 s），暴露出弱网档三个判定缺陷：① tolerant 漏关码率判据（弱网下瞬时码率随自适应与重传在 205~427 kbps 摆动，目标 320 kbps）；② 字段文档写着 0 = 不判，而判定式 deviation 大于 tolerance 在 0 时退化成全判；③ 快照总量配额被单类独占，留存的 200 条全落在 2692..8293 s，后面 5.7 h 一条现场都不剩。已修：档位集中到 SoakThresholds::weak_network、码率以 bitrate_tolerance_pct_x100 = 0 显式关掉并补回归测试、快照配额按类（默认每类 25 条），报告新增 violations_total / violations_by_kind / last_violation_at_secs / last_violation_kind / violation_limit_per_kind。同参数 90 s 对照：tolerant 档 0 异常 / exit 0，去掉 tolerant 18 条异常 / exit 1（放宽只发生在宽容档）。8 h 关键数字：掩盖 950 帧 = 0.066%（弱网门槛 1%）、注入自账 51527 丢包 = 2.01%、末次码率 349 kbps / 水位 120 ms / RTT 41.8 ms / 漂移 -4 ppm、欠载 4307 / 迟到 4414（弱网档不判）。提交 de21d0b；详见 docs/22 §9 与 docs/24 §3。 2026-09-17 8 h 弱网长跑' }
    @{ T = '[M2] 遥测面板（5 分钟曲线 + CSV 日志导出）'; M = 'M2'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成（路线图 M2 交付物「遥测面板：曲线 + P50/P95 + 日志导出」）。TelemetryRow 是独立的持久化契约（10 列 camelCase，刻意不复用界面字段名，避免界面改名污染用户已导出的文件）；render_telemetry_csv 纯函数（表头 + 一行一采样点、换行收尾、小数位固定）；write_telemetry_csv 落在 <用户目录>\AudioLink\telemetry-<毫秒>.csv（不弹文件对话框，无头/CI 可跑），export_telemetry 命令把路径回给 UI。前端 useAudioLink 维护 500 ms 一采样点、上限 600（5 分钟）的环形历史；TelemetryPanel 手绘 4 条 SVG 折线（端到端延迟 / 缓冲水位 / 码率 / 丢包率，纵轴按窗口最大值归一化，non-scaling-stroke 防变形）+「导出 CSV（N 点）」按钮。前后端各有一份镜像测试（Rust from_view / TS telemetryRowOf），字段漂移编译期即红。质量门：内核 fmt / clippy -D warnings / 全量测试、桌面 clippy / 15 项测试、pnpm build（tsc 严格 + vite）全绿。未做：真实窗口的曲线观感与点击导出落盘的人工复核（本机无头），同 docs/13 口径。提交 87cb059；CI run 35079292910（core / android / desktop / version-consistency）全绿。详见 docs/25-m2-telemetry-panel.md。' }
    @{ T = '[M3] 多设备与同步：时钟同步全流程 + 预约播放 + 同步组 + sync-measure'; M = 'M3'; P = 'P2'; S = 'In Progress'; B = '组内 ±10 ms（P95）；§6 的 200 样本窗口 + 回归漂移估计在此落地。2026-09-16：交付物 5（双机录音对齐工具 tools/sync-measure）已完成 —— M3 的「量」这一半就绪（详见 docs/27-m3-sync-measure.md）。剩余交付物：多会话管理（并行推 ≥8 台）、临时同步组（勾选成组 / 动态加入退出 / 成员质量展示），以及真机双机同期录音验收（±10 ms P95）。2026-09-16：交付物 3（预约播放：接收端按 epoch 排播）已完成 —— 新增 audiolink-engine::epoch（§7 换算 + 等待/播放/丢弃三分支，8 项单测）、播放线程接线（未到目标补静音等待且不推进游标、过期 20 ms 丢弃并计 late_drops，只在显式设置排播时介入）、首个数据报的 seq → sample_index 换算基准、Engine::schedule_playout API 与 PlayoutScheduled 时间线；3 项播放面测试 + 引擎 133 项单测全绿。未接 GROUP_EPOCH 载荷与真机双机验证（见 docs/28）。2026-09-16 续：0x43 协议通道（docs/29）与组管理三帧 + 成员账本（docs/30）也已完成，2026-09-16 再续：多会话的共享采集枢纽与 start_send_many 已完成（docs/33），每会话音量（SET_GAIN 接线）与真机三台同时出声验收（±10 ms P95）是 M3 剩余项。 2026-09-17：状态从 Todo 修正为 In Progress —— 五条交付物（多会话 / 时钟同步 / 预约播放 / 临时同步组 / sync-measure）全部有 Done 条目，验收四条里「并发」（multi_session）与「动态」（dynamic_join，运行中第 3 台加入且前两台各新增 387 840 个样本）已有回环自动化证据；剩「同步」（组内 ±10 ms P95 的真机同期录音）与「时钟抖动 ≤ 2 ms 的遥测曲线」以及 ≥ 8 台压测。' }
    @{ T = '[M3] 动态加入回环验证（运行中第 3 台加入，前两台不中断）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成。M3 验收表四条（并发 / 同步 / 动态 / 时钟）里，并发由 multi_session 覆盖、同步要真机同期录音、时钟由 clock_sync 覆盖 —— 只有「动态」没有任何自动化证据，而它最容易出问题：新会话加入要新建采集订阅、编码器、QUIC 会话，任何一处争用都可能让已在跑的会话停顿。新增 core/crates/audiolink-engine/tests/engine/dynamic_join.rs：两台先配对开流跑 4 s（确认都在出声），第三台在运行中加入（连接 → PIN → 开流），再跑 4 s 量三台各自的样本增量。判据刻意用「接收侧 sink 的样本增量」而不是「状态还是 Streaming」—— 状态是采样值，断流几百毫秒可能采不到；样本数不增长才是直接证据。实测：前两台各新增 387 840、第三台 382 080 个样本，理论满额 = 4 s × 48 kHz × 2 声道 = 384 000 —— 第三台的加入没让前两台掉一个样本。本测试跑在 core-heavy 的 test 步骤里，不额外占用 CI 时间。真机三台同时出声（组内 ±10 ms P95）仍需设备。详见 docs/33-m3-multi-session.md §6。' }
    @{ T = '[M3] 组内同步回环护栏（两端播放时刻差 P95 ≤ 10 ms）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成。M3 验收线「组内偏差 ≤ ±10 ms（P95）」的验收方法原本写的是「双机同期录音 + 波形对齐」，那要两台设备；但这条指标在同一进程里就能量：两个接收端共用同一个单调时钟，记下各自 sink 写出每一帧的时刻，「第 k 次写出」的时刻差就是它们的播放偏差。新增 core/crates/audiolink-engine/tests/engine/group_sync.rs（1 发送 + 2 接收 + 建组同一 epoch 排播 + start_send_many，跑 6 s 逐帧比较）。量法出两个数字：absolute（偏移 0，含起播差，对应验收线）与 aligned（扣掉整数帧偏移后的抖动，护栏断言用）。连跑 4 次：后三次 absolute P50 0.02–0.51 ms、P95 0.56–0.80 ms（偏移 0 帧，几乎完全同步），远优于 ±10 ms。验证：engine 169 项全过、fmt / clippy 零警告。详见 docs/33-m3-multi-session.md §7。' }
    @{ T = '[M3] 观察：组内起播偶发错开一帧（20 ms，超 ±10 ms 验收线）'; M = 'M3'; P = 'P2'; S = 'Todo'; B = '2026-09-17 观察到（1/4 次跑）：两个接收端的**起播时刻整整错开一帧**（absolute P50 = 19.65 ms、P95 = 20.14 ms），而 M3 验收线是 ±10 ms —— 那一次不达标。同一测试连跑 4 次的另外三次都是偏移 0 帧、P95 < 1 ms，所以既不能断定是稳定缺陷，也不能断定是纯偶然。要做：① 多跑若干次统计出现频率；② 定位根因（怀疑是 epoch 换算到本地帧边界时的取整或时机：两个接收端对同一个 epoch 时刻做换算，若一个落在帧边界前、另一个落在后，就会差一帧）；③ 查清后决定是修换算精度，还是把验收线的口径改成「稳态偏差」（不含起播）。**在查清之前不要写成断言**：会偶发红的断言只会被忽略。 2026-09-17 补充观测：连跑 5 次里**2 次**出现错一帧（absolute P50 ≈ 19.7 ms / P95 ≈ 20.2 ms），另外 3 次偏移 0 帧、P95 < 1 ms。**关键线索**：错帧的那两次在扣掉 1 帧偏移之后 P95 只有 0.04–0.79 ms —— 说明**排播本身很稳，问题纯粹在「起播对齐差一帧」**。下一步优先定位 epoch → 本地播放时刻的换算：是否有一侧落在帧边界另一侧而没有多等一帧。' }
    @{ T = '[M3] 预约播放：接收端按 epoch 排播（§7 目标时刻 + 迟到丢弃）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（路线图 M3 交付物 3）。新增 audiolink-engine::epoch（纯逻辑）：EpochSchedule + local_target_us（local(epoch) = epoch_local_us − offset，offset = 对端 − 本机）+ PlayoutAction 三分支（未到目标等待 / 到达 20 ms 门限内播放 / 超过则丢弃）；8 项单测把符号、lead、边界与 u32::MAX 样本序号都钉住。播放线程接线：有排播时未到目标就补静音等待且**不推进播放游标**（那帧还要在目标时刻播），超过目标 20 ms 的帧丢弃并计入 late_drops，首次排播发一条 EngineEvent::PlayoutScheduled 作为验收时间线；没设置排播时完全走 M1/M2 的本地游标，老行为一个字没改。换算基准取自本流首个数据报的 (seq, sample_index)，之后按 48 kHz 帧长推算。控制面新增 Engine::schedule_playout(peer, Option<EpochSchedule>) → SessionCommand::SchedulePlayout。3 项播放面测试 + 引擎 133 项单测全绿。未做：§7 的 buffer_ms/dac_latency_ms 补偿项、GROUP_EPOCH 载荷接线（目前靠上层显式调用）、真机双机起播对齐验证。详见 docs/28-m3-scheduled-playout.md。提交 20218cb；CI run 35085530753 四个 job 全绿。' }
    @{ T = '[M3] 组控制帧（GROUP_CREATE / JOIN / LEAVE / EPOCH）载荷与接线'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（四帧全部接线：0x43 见 docs/29，三帧见 docs/30）。新增 GroupCreatePayload{group_id, epoch_id, epoch_local_us, lead_ms, members}、GroupJoinPayload{group_id, member}、GroupLeavePayload{group_id, member}（postcard，成员身份用 NodeId 指纹）；dispatch 把三帧从「本里程碑不实现」计数里移出并补上编解码映射与样本（覆盖度测试同步更新，未实现计数只剩 SET_VOLUME_LOCK / TELEMETRY_PUSH）；引擎侧新增组账本（group_id → epoch/lead_ms/成员 BTreeSet）与 API：create_group(成员, lead_ms) -> group_id、join_group、leave_group、groups() -> 快照，以及 EngineEvent::GroupUpdated；接收侧收到 GROUP_CREATE 就用本机时钟偏移换算并排播（与 0x43 同一条路径）。动态加入语义：新成员除 JOIN 外还会补一条 GROUP_EPOCH（它需要组基准才能排播），老成员不受影响。端到端（真双 Engine + 真 QUIC + 真 PIN）：建组后账本恰好一个组、成员表就是被点名的对端、lead_ms 原样、成员排播用的 epoch 与建组帧一致、退光后组条目被清掉。未做：桌面/Android 的勾选成组面板与成员同步质量展示、真机三台同时出声（±10 ms P95）、多会话。详见 docs/30-m3-group-management.md。' }
    @{ T = '[M3] GROUP_EPOCH 载荷与接线（发送端指定组基准 → 接收端排播）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。新增 GroupEpochPayload{epoch_id, epoch_local_us, lead_ms}（§4.1 的 0x43，postcard）；dispatch 层把 0x43 从「本里程碑不实现」计数里移出，补上 ControlRequest::GroupEpoch 与 op()/encode_body() 映射（覆盖度测试与 L1 往返测试同步更新，样本表补样本）；接收侧收到 GROUP_EPOCH 后用本机时钟偏移换算并写入排播（与 Engine::schedule_playout 同一条路径）；发送侧新增 Engine::announce_group_epoch(peer, epoch_id, lead_ms)，epoch_local_us 取本机单调时刻。端到端（真双 Engine + 真 QUIC + 真 PIN + NullPlayout）：0x43 送达、epoch_id 原样到达接收端、target_local_us 是换算后的本机 µs、等待量落在「帧的流内时刻 + 提前量」量级。本轮实测还澄清了一个容易想错的地方：target = local(epoch) + sample_index/48000 + lead，所以接收端等的不是 lead 而是「流内时刻 + lead」；由此推论 epoch 必须与当前推流位置对齐，否则目标落在过去、帧会被 age 判定全部丢掉（这是既定语义，不是缺陷）。未做：GROUP_CREATE/JOIN/LEAVE 组管理三帧、真机双机同时出声验证、§7 的 buffer/dac 补偿项。详见 docs/29-m3-group-epoch.md。' }
    @{ T = '[M3] 桌面端同步组面板（勾选成组 / 动态加入退出）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。引擎侧组账本与四个组控制帧就绪后，把「同步组」接成界面：新增 4 个 Tauri 命令（list_groups / create_group(id_shorts, lead_ms) / join_group / leave_group）、桥接层视图转换（组成员短码与 PeerView 同口径，epoch_id 字符串化 —— u64 在 JS 里只有 53 位安全整数，直接传数字会悄悄丢精度）、视图形状 GroupView/GroupMemberView、前端类型 + 4 个 IPC + hook 状态与动作、以及 GroupPanel 组件（可加入对端勾选列表 + 提前量输入 + 建组按钮 + 组卡片：成员、epoch、逐成员退出、未入组成员一键加入），挂载在遥测面板上方。验证：Rust 视图转换单测（epoch 以 16 位 hex 出网、成员短码口径）、tsc --noEmit 严格模式 + vite build、桌面 clippy/测试与内核全量 fmt/clippy/测试全绿。未做：成员同步质量展示（需每成员时钟估计质量）、事件驱动自动刷新、真机三台同时出声（±10 ms P95）、多会话。详见 docs/31-m3-group-panel.md。' }
    @{ T = '[M3] 成员同步质量展示（§6.5 分级随成员表出网）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。协议 §7 明确要求「某成员 Poor 质量 → UI 必须明示该设备同步质量差」，而质量此前压根没出网。本次把 GroupSnapshot 的成员从裸指纹改为 GroupMember{id, quality, offset_us}：groups() 为每个成员填 §6.5 的时钟分级（取自该会话自己的估计；还没有估计时按 Poor 处理 —— 没有估计等于不可同步，不能默认 Good），并先放掉组表锁再查会话表以避免「组表 ⇄ 对端表」两把锁同时持有。桌面侧 GroupMemberView 增加 quality（good/fair/poor 字符串）与 offsetUs，面板按分级上色（poor 红字「同步质量差」、fair 琥珀、good 绿），悬停显示偏移 µs 或「还没有时钟估计」。验证：引擎端到端断言成员表与质量分级（三个确定值之一）、桌面视图转换单测（质量字符串透传 + offset）、tsc 严格 + vite build、内核与桌面 clippy/测试与 fmt 全绿。未做：事件驱动刷新、质量变化的显式提示、真机三台同时出声、多会话。详见 docs/32-m3-member-quality.md。' }
    @{ T = '[M3] 多会话：共享采集枢纽 + start_send_many（一路采集喂 ≥3 台接收端）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（路线图 M3 交付物 1 的结构部分）。核心判断：共享采集不是优化而是**正确性**问题 —— 各会话各自采集时读取起点与丢样彼此错开几十毫秒，接收端按同一个 epoch 播放时这点错位会原封不动加到组内偏差上（M3 验收是组内 ±10 ms）。实现：CaptureHub（一路 CaptureSource → 切片 → 统一分配 seq/sample_index → 广播，容量 8 帧、慢会话丢旧帧不拖住采集）+ 每会话编码线程 session_encoder_main（订阅共享帧、用本会话 codec/码率编码）+ 引用计数生命周期（第一个会话启流创建、最后一个停止时停采集、下一个会话重建）+ Engine::start_send_many（每台一份结果，一台失败不影响其它）+ 同引擎必须同帧长的显式约束 + 封口时刻在枢纽只记一次。编码留在会话侧是为了各会话能各用自己的码率（§8 自适应按对端丢包各自决策）。验证：HubClock 单测（编号与 u32 回绕）+ 端到端 tests/multi_session.rs（1 发 3 收，真 QUIC + 真 PIN；三台接收侧链路码率 ≈ 321–328 kbps 即三路都在收帧）+ 引擎全量与桌面/内核 clippy、fmt 全绿。**发现（已记 docs/33）**：接收端 peers() 里查不到发起端（accept 一侧会话表未登记），本轮改用接收侧链路码率当判据；这是既有行为待单独核。未做：≥8 台真机压测、每会话音量（SET_GAIN 未接线）、真机三台同时出声验收。详见 docs/33-m3-multi-session.md。' }
    @{ T = '[M3] 每会话独立音量（SET_GAIN / SET_MUTE 接线 + 播放侧渐变）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（补上 M3 交付物 1 的「每会话独立音量」）。新增 audiolink-engine::gain（纯逻辑）：GainState 当前值 → 目标值按步长逐帧逼近，f32 增益严格转千分点整数（内部一律整数比较，浮点参数不可复现），NaN/inf/负数/超上限一律拒绝而**不静默夹到合法值假装成功**；播放侧每帧写前取一次增益并乘到样本上（每帧最多一个步长 —— 硬切增益就是爆音）；增益状态挂在播放句柄上，**每会话一份**（多会话各调各的，采样时间轴仍共享）；ControlRequest::SetGain/SetMute 从「明确不做」变成真的生效（含 stream_id 校验），SET_MUTE 用 50 ms 渐变；新增 Engine::set_peer_gain(peer, gain, ramp_ms)（发送端调接收端音量，非法值在发送端就拒绝、不发到线上）。验证：gain 纯逻辑 8 项单测（分步/零渐变/极小差值/往返/超限拒绝/严格转换/放大）+ 端到端 tests/gain_control.rs（真 QUIC + 真 PIN + 记录写出的 PCM：基线 RMS 0.1772 → 静音 0.0000 → 恢复 0.1773；越界 3.0 在发送端 Err）+ 引擎 142 单测与全部集成测试、桌面全量、内核与桌面 clippy、fmt 全绿。未做：UI 音量控件、真机听感验证、音量回读、真机三台同时出声。详见 docs/34-m3-per-session-gain.md。' }
    @{ T = '[M3] 接收端对端可见性核对（澄清误报 + 正式断言）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。上一轮曾记下「接收端 peers() 查不到发起端」的疑点；本轮按时序采样（0.5s/2s/3.5s/5s）复核后确认那是**测试把断言写在 shutdown 之后**造成的假象 —— 链路上对端表一直是 1 条会话、状态在 Streaming/Degraded、遥测有值，只有关闭之后才清 0（正常清理）。处置：multi_session 增加正式断言（链路上接收端恰好看到发起端一条会话，id 与状态正确）+ 反向断言（关闭后对端表必须清空，否则 UI 会挂着不存在的设备）；docs/33 §4 与交接条目同步更正，不让错误结论留在仓库里。教训已写进 docs/35：断言的位置本身就是结论的一部分（shutdown 后查表、渐变期测稳态、priming 前量队列是同一类错误）。顺带把 SET_GAIN 通到桌面外壳（EngineBridge::set_peer_gain + set_peer_gain 命令 + api/hook 动作，渐变 200 ms）。未做：UI 滑块（对端卡片的三元 JSX 需要包 fragment 才能并列渲染，本轮未冒险改结构）。详见 docs/35-receiver-visibility-correction.md。' }
    @{ T = '[桌面] 音量滑块（set_peer_gain 已通到 IPC，UI 未接）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。对端卡片在推流中显示音量滑块（0–200%，range 0/2 step 0.05，aria-label 与 title 都写明「拖动时按 200 ms 渐变生效」），经 onGain → api.setPeerGain(id_short, gain, 200) → 桥接 resolve_peer → Engine::set_peer_gain 下发；非法值由引擎边界拒绝并人话化，成功用 notice 报「音量已设为 N%」。实现上刻意**没有**动原来那个「开始/停止/等待配对」的三元结构：滑块作为独立的 streaming 条件块渲染在操作区之上，避免为了并列放两个孩子去包 fragment（上轮就是在这里停手的）。卡片顶部注释同步更新（原写着「不做音量滑块」）。验证：tsc --noEmit 严格 + vite build、桌面 clippy/测试、内核全量门禁全绿。' }
    @{ T = '[桌面] 同步组面板改为事件驱动刷新（GroupUpdated → audiolink://groups）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。引擎侧本来就在建组/加入/退出时发 EngineEvent::GroupUpdated，但外壳只记日志、面板要用户手动点刷新。现在：桥接层新增 EVENT_GROUPS（audiolink://groups），GroupUpdated 分支除了日志还 emit 一条轻量信号（group_id/epoch_id/members 三元组）；前端 ipc 增加 EVENT_GROUPS 常量与 subscribeEvents 的 onGroupUpdated handler；hook 收到信号就 refreshGroups() 拉一次最新列表（明细仍以 list_groups 为准，信号只表达「变了」）。不做轮询的理由：建组/加入/退出都是低频人工动作，事件驱动既省 IPC 也不会漏。验证：桌面 clippy（-D warnings）/测试、tsc 严格 + vite build、内核全量全绿。' }
    @{ T = '[M4] 混音器（多路求和 + 软限幅 + 每路增益/静音）'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。新增 audiolink-audio::mixer（纯逻辑）：PcmMixer 多路求和、软限幅（拐点 0.7 以上指数逼近 ±1，连续单调永不削顶）、每路增益/静音、缓冲满丢最旧、FR-12 的 8 路上限；每次混音返回 MixStats（参与路数 / 被限幅样本数 / 限幅前峰值）并可累计，让「听起来有没有爆」有数字可看。引擎接线用 **owner 模式**：同一台接收端只打开一次播放设备 —— 第一个会话是 owner，它的播放线程照旧跑 M1/M2 的全套调度（抖动深度、欠载补静音、迟到丢弃、§7 排播），只是写出去的内容从「自己那一帧」变成混音器输出；其余会话继续跑自己的调度、只把帧混进去不碰设备。这么做的理由是 M1/M2 的播放纪律是三轮调出来的，混音只该换「写什么」而不是重写「什么时候写」。每路增益走 §4.1 的 SET_GAIN（落到本会话那条混音输入上，多会话各调各的）；会话停止时把自己的源摘掉（否则重连几次就撞上限）；超限报 STREAM_LIMIT。验证：mixer 11 项单测 + tests/mixer_convergence.rs（两个发送端 → 一个接收端，真 QUIC + 真 PIN + 记录 PCM：两路混音 RMS 0.2501 → 静音 A 路后 0.1769，比值 0.707 = 1/√2，即不相关信号去掉一路的功率半减，定量证明两路都真的进了输出）+ 引擎全量与桌面/内核 clippy、fmt、前端 build 全绿。未做：Android 内录/麦克风、能力协商与降级、多路时钟对齐（不同源按各自 epoch 换算后再混）、真机无爆音验收、8 路压测。详见 docs/37-m4-mixer.md。' }
    @{ T = '[M4] 多路混音对齐观测（MixSnapshot + 掉队帧统计）'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。mixer 的 MixStats 增加 missing_sources，PcmMixer 累计 partial_frames/total_frames 并给出 MixSnapshot；引擎侧新增 Engine::mixer_stats()->Option<MixSnapshot>（源数 / 帧数 / 掉队帧 / 限幅样本）。掉队帧是对齐程度最直接的读数：两路都持续供帧时它应长期为 0，某一路掉队会立刻涨。实测 tests/mixer_alignment.rs（两个发送端 → 一个接收端，真 QUIC + 真 PIN）：源 2 路 · 帧 298 · 掉队帧 1（0.3%）· 限幅样本 0 —— 稳态下两路都在稳定供帧，混音不靠补静音撑场面。mixer 单测 13 项（新增 2 项：对齐时 missing_sources 恒 0 且 partial_frames=0；一路掉队时每帧记一次缺席）。详见 docs/38-m4-mixer-alignment.md。' }
    @{ T = '[M4] 桌面「广播共同基准」入口（提前量 + 会话计数）'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。补上 §5 记的第三条缺口（没有入口，只能从引擎 API 调）：引擎 Engine::broadcast_epoch(lead_ms)（已有）→ Tauri 命令 broadcast_epoch(lead_ms) -> 发出的会话数 → 面板上的「广播共同基准」按钮 + 提前量输入（默认 200 ms）。**为什么提前量默认给宽**：发送端收到基准后会等到那个时刻才从编号 0 开始发，提前量太小则还没等到就已经过去了（那一段采集被整段丢掉），太大只是多等一会 —— 两种错法代价不对称，所以默认取宽的那边。**按钮只能由接收端按**，这不是 UI 约定而是事实：broadcast_epoch 的语义就是「我（混音方）指定共同原点」，发送端按它没有意义（它正是要被对齐的那一方）。成功后提示「已向 N 条会话广播共同基准（提前量 X ms）」；没有已连接对端时引擎拒绝，错误原因由错误层翻成人话（不在组件里）。详见 docs/40 §6。' }
    @{ T = '[M4] 桌面「多源对齐」面板（每路编号 + 当前跨度 + 对齐结论）'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。把内核的「跨度」读数搬到界面：接收端每包的 (编号, 到达毫秒) 快照 → Engine::stream_axes() → 纯函数 alignment_view(axes, now_ms) → Tauri command alignment → 前端 1 Hz 轮询 → AlignmentPanel 显示每路「最近编号 / 推算编号 / 到达时刻」与当前跨度。判据与阈值：跨度 ≤ 960 样本（1 帧 / 20 ms）= aligned（采样级对齐达标）；> 960 = drifting（多半没广播过共同基准）；有效读数不足两路 = unknown（**不给数字**——一路无法比较，也不拿一路硬凑）。阈值取一帧是刻意的：混音器按帧对齐，一帧以内的偏差在混音上听不出来，而 M4 实测对齐结果是 144 样本（3 ms），离阈值还有 6 倍余量。**为什么 1 Hz 轮询而不是事件驱动**：读数在引擎里每包都在变（50 包/秒 × 路数），事件驱动会变成每包一次 IPC，而界面只需要看趋势；没有对端时定时器不启动。alignment_view 纯函数单测 5 项（单路 Unknown、144 样本 Aligned、72048 样本 Drifting、两路皆无读数 Unknown、一路有读数一路无 Unknown）。已知缺口：真机场景未验（手机与 PC 不同子网）、无历史趋势、没有「一键广播基准」按钮。详见 docs/40-m4-alignment-panel.md。' }
    @{ T = '[M4] 采样级对齐的直接观测入口：接收端暴露每路 sample_index ↔ 到达时刻'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。接收端每收到一个音频数据报就把「最近一帧的 sample_index ↔ 到达时刻」打包成一次 64 位原子写（高 32 位毫秒、低 32 位编号，读者不会读到撕裂组合；实时路径不加锁不分配），Engine::stream_axes() 暴露每路的 StreamAxis{peer, sample_index, at_ms}，StreamAxis::index_at(now_ms) 用同一个「现在」推算该路当前编号 —— 两路跨度就是时间轴错位量。**它当场抓出一个真缺陷**：补上观测后第一条断言就红了 —— 对齐前跨度 72096 样本（1.5 s，符合刻意制造的错位），对齐后仍是 72192，说明对齐根本没生效。根因是上一轮只把 0x44 加进 OpCode 枚举，忘了加进 OpCode::ALL 与 OpCode::from_u8，于是 dispatch 把它当未知命令码忽略（IgnoredUnknownOp），发送端从未收到共同基准 —— 而这正是上一轮那个绿灯测试测不出来的：它只验证 broadcast_epoch 返回 2（帧发出去了），没验证对端处理了它。修好后：对齐前跨度 72048 样本 → 对齐后 144 样本（3 ms，1 帧 = 960 样本）。顺带被三处既有护栏拦住并修掉（OpCode::ALL 数量断言、net 的 24→25 opcode 全扫、engine dispatch 样本表）。详见 docs/39 §6。' }
    @{ T = '[M4] 多源共同时间基准（接收端广播 epoch + 发送端预约发送）'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。§7 的 GROUP_EPOCH 是「发送端指定、接收端排播」，只能让同一发送端 → 多台接收端对齐；M4 的多源拓扑（2 部手机 → 1 台 PC 混音）里两个发送端彼此独立，sample_index 的原点分别是各自启流瞬间，接收端按编号混音取到的不是同一时刻的声音。本轮把方向反过来：新增控制帧 RECEIVER_EPOCH（0x44，接收端 → 发送端，复用 GroupEpochPayload），接收端作为基准来源广播 epoch（Engine::broadcast_epoch(lead_ms) 遍历已连接会话发出），发送端收到后用自己的 §6 时钟偏移换算到本端轴（本端时刻 = 对端时刻 − offset_us），再让采集线程的 HubClock 把编号 0 点钉到它：到点之前一帧都不发（那些帧的编号在接收端没有可比性），到点后编号从 0 起算、seq 不受影响（它只管丢包检测）。基准用 AtomicI64 传给采集线程（i64::MIN = 未收到），实时路径不加锁不分配。实测（真实双 Engine + 真实 QUIC，tests/receiver_epoch.rs）：广播覆盖 2/2 条会话、对齐后两路仍各占一路、供帧未被打断（148 → 298 帧 / 3 s）、掉队帧 1/298 = 0.3%；HubClock 单测 3 项（到点前不发、到点后从 0 起算、重新对齐不动 seq）。**仍然诚实的缺口**：这测的是「广播到达 + 对齐不打断供帧」，真正的采样级判据（同一编号 = 同一时刻，误差 < 1 帧）还读不到 —— 接收端没有暴露每路 sample_index ↔ 到达时刻，已另立待办。**2026-09-16 第二轮修正**：本条当时报「完成」并不准确 —— 0x44 只加进了 OpCode 枚举，漏了 OpCode::ALL 与 from_u8，发送端实际从未收到共同基准（dispatch 当未知命令码忽略）。由本轮补上的观测入口（Engine::stream_axes）当场抓出并修复；修复后实测两路编号跨度 72048 → 144 样本（3 ms）。详见 docs/39 §6。详见 docs/39-m4-common-time-base.md。' }
    @{ T = '[M3] 双机录音对齐工具 sync-measure（脉冲 + 波形对齐，输出偏差与漂移）'; M = 'M3'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（路线图 M3 交付物 5）。新增 audiolink-tools::syncmeasure（纯逻辑）+ --bin sync-measure：自研 WAV 解析（PCM 16/24/32 与 float 32/64、EXTENSIBLE、奇数块填充、data 截断按整帧）、脉冲粗检测（快攻击慢释放包络 + 阈值穿越插值）、亚采样精细对齐（脉冲邻域归一化互相关 + 抛物线插值）、统计与判定（均值 / P50 / P95(|·|) / 极值 / 漂移 ppm 对「A 侧时刻 → 偏差」线性回归）、JSON 报告；退出码 0 达标 / 1 超标 / 2 用法 / 3 输入或检测失败。测具先被量一遍：--self-test 合成已知真值（4.7 ms 偏差 + 120 ppm 漂移）逐对比对，实测单对最大误差 0.010 ms、漂移 1.0 ppm。踩到并处理一个真坑：单一频率长正弦的互相关有周期歧义（偏差散开约 1 ms），夹具改用宽带噪声突发，且搜索范围内出现几乎等高的另一峰时该对标 ambiguous 并写进报告与 notes（不假装没看见）。测具不撒谎：静音 / 纯直流 / 检测不到脉冲 / 脉冲不足 / 波形对不上（NCC < 0.5）一律明确报错，负向用例（脉冲串 vs 伪随机噪声）必须报错。端到端：--self-test --write 写出两段真 WAV（各 192000 帧）再走完整命令行，6 对 NCC ≈ 1.0、逐对偏差 4.708–5.000 ms（真值 4.7 + 0.06·i）、判定 within、退出码 0。16 项单测 + 4 项 CLI 测试。真机双机同期录音验收尚未执行（工具已就绪）。提交 6e2fddd；CI run 35083496842 四个 job 全绿。详见 docs/27-m3-sync-measure.md。' }
    @{ T = '[M4] 网状与混音：Android 内录/麦克风 + PC 播放 + 混音器 + 能力协商'; M = 'M4'; P = 'P3'; S = 'In Progress'; B = 'FR-06/07/08/12；内录受 allowAudioPlaybackCapture 限制需 UI 说明。2026-09-16：交付物 3（混音器：多路求和 + 软限幅 + 每路增益/静音）已完成，PC 侧汇聚机制就绪（docs/37）。剩余：① Android 内录（AudioPlaybackCapture）与麦克风路径（需真机 + allowAudioPlaybackCapture 实测）；② 能力协商与降级（CAP_UNSUPPORTED 的 UI 置灰与说明）；③ 多路时钟对齐：**观测部分已做**（MixSnapshot + 掉队帧，docs/38），**共同时间基准仍是缺口**（已拆成独立待办：接收端广播 epoch + 发送端预约发送）；④ 真机「2 部手机 → PC 无爆音」与「PC ↔ 手机双向」验收；⑤ 8 路压测（上限已实现，超限报 STREAM_LIMIT）。' }
    @{ T = '[M4] 能力协商（内核侧）：握手期能力位图 + CAP_UNSUPPORTED 拒绝路径'; M = 'M4'; P = 'P1'; S = 'Done'; B = '2026-09-17 完成（M4 交付物 4 的内核侧）。问题很具体：连得上不等于能互相说话 —— 一端只有 Opus、另一端只有 PCM 时握手会成功，一开流必然失败，用户看到的是「连上了却没声音」，原因要从几十行日志里翻。做法：新增 audiolink_types::Capabilities 位图（OPUS 必需；PCM16/CAPTURE/PLAYOUT/SYSTEM_LOOPBACK/MICROPHONE/MIXER/GROUP_EPOCH 可选）+ intersect / missing_required / describe / unknown_bits；HELLO 加 caps、HELLO_ACK 加 caps + agreed_caps；握手期算交集，缺必需位当场拒绝，沿用版本不匹配的既有范式（accepted=false + 人话 reason + 事件错误码），用既有的 1005 CAP_UNSUPPORTED，没有新增错误码。拒绝原因把双方各自有什么、缺哪一项写在一行里。两条设计判断：① 只有不可替代的能力才标必需（现在只有 Opus）—— 标多了会把「能用但功能少」误判成「连不上」，比不做协商更糟；② 可选位缺失不拒绝，交给调用方降级。另加双向复核：发起方自己再算一遍交集与对端报来的 agreed_caps 比对，将来只改一侧时立刻失败。Capabilities::CURRENT 只声明内核真做到的（内录与麦克风要平台侧接上才算，现在不声明）。实测：位图单测 5 项（core/crates/audiolink-types/tests/capabilities.rs）+ 握手单测 2 项，引擎 146 项全过、clippy 零警告、fmt 通过。测试还抓出一个小问题：describe 对「全是未知位」的位图返回「无」，界面会显示成「对端没有能力」，而真相是对端比本端新；已改为输出「未知能力」。详见 docs/46-m4-capability-negotiation.md。' }
    @{ T = '[M4] 能力协商（界面侧）：引擎查询 API + 对端能力展示'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成（第二轮）。上一轮把协商做进握手，但结果只有 Handshake::agreed_caps() 能看见 —— 界面看不到，用户仍然不知道「为什么这个功能对这一台用不了」。本轮接通四层：HandshakeEvent::Established 带上 local_caps / peer_caps / agreed_caps（自包含，会话层不用回头问握手对象）→ PeerSession.capabilities → PeerStatus.capabilities → 桥接层 PeerView.capabilities。**位图在 Rust 侧就翻成人话**（PeerCapabilitiesView：local / peer / agreed / missingOnPeer[]）—— 把 1 << 3 丢给前端等于让每个前端各实现一遍解释，迟早不一致。界面：对端卡片多一行「可用：…」，本端有而对端没有的能力非空时补一句琥珀色「对端不支持：…」；missingOnPeer = local & !peer，是置灰那一半的直接输入。**契约形状测试立刻抓到变化**：PeerView 多了字段 → peer_and_local_json_shape_match_contract 变红（字段名漂移会让前端静默拿到 undefined，这正是它的用途），已扩成「未协商 null」与「已协商含嵌套与数组」两个形状。验证：引擎 170 项、desktop 27 项、pnpm build（tsc 严格 + i18n 键与占位符护栏）全过；fmt / clippy 零警告。i18n 新增两个键中英齐备。详见 docs/46-m4-capability-negotiation.md §8。' }
    @{ T = '[M4] 能力协商（降级）：依赖能力的入口按协商结果置灰'; M = 'M4'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成（第三轮，补上界面侧的「降级」那一半）。§8 只做到「说明」—— 卡片上写清对端缺什么；本轮把说明变成行为：建组勾选列表里对端交集不含 GROUP_EPOCH 时复选框直接禁用。**一条必须坚持的边界**：界面判断不能去解析中文文案 —— 拿 agreed 那串中文去 includes 会「改一次文案断一次判断」，而且断得静默（界面照常显示，只是不再置灰）。所以位图现在出两条：agreed（人话，给人看）与 agreedKeys（键，给判断用）；Capabilities::key() 与 name() 并列存在，并有测试钉住「每个已知位都有独立且非 unknown 的键」与「键不重复」。**另一个刻意的区分**：capabilities === null（还没协商完）也禁用，但写「等待能力协商…」而不是「不支持」—— 「等一下」与「别等了」是两件事，混成一句会让用户在握手那几百毫秒里以为设备不兼容。验证：types + engine 171 项、desktop 27 项、pnpm build（tsc 严格 + i18n 键与占位符护栏）全过，fmt / clippy 零警告。仍未做：无损档 PCM16 与混音路数在界面上还没有对应控件（等有了按同一模式处理）；平台能力注入仍缺（with_capabilities 口子已开）。详见 docs/46-m4-capability-negotiation.md §8.3。' }
    @{ T = '[M4] 平台能力注入：EngineConfig 声明 + 桌面内录 / Android 现状'; M = 'M4'; P = 'P1'; S = 'Done'; B = '2026-09-17 完成。此前 Capabilities::CURRENT 被写死在握手构造函数里，于是「所有设备都声称自己一样」—— 能力协商只剩形式。现在 EngineConfig.capabilities（默认仍是 CURRENT）由平台侧声明并带进握手：桌面端（Tauri）声明 CURRENT | SYSTEM_LOOPBACK（WASAPI loopback 采集已实现，见 docs/13），Android（FFI）保持 CURRENT 不声明内录 —— **未实现的就不声明**，并在代码里留了注释说明接上之后怎么打开那一位。**端到端证据**（不是「字段赋值对不对」）：新增 core/crates/audiolink-engine/tests/engine/capability_negotiation.rs，起两个真实 Engine（真 QUIC + PIN 配对），一端声明内录、另一端不声明，断言**对端** peers() 里读到的那份能力 —— peer 位含内录、local 位不含、agreed 交集不含，正是界面按 missingKeys 置灰用的那个输入。验证：types + engine 172 项测试全过（新增 1 项端到端）、desktop 27 项、fmt / clippy 零警告。仍未做：Android 内录本身（AudioPlaybackCapture）、无损档 PCM16 与混音路数在界面上还没有控件。详见 docs/46-m4-capability-negotiation.md §8.3.5。' }
    @{ T = '[M5] 第三方声明投放（随包分发 + 关于面板）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。把「声明躺在仓库里 ≠ 用户看得见」这一条做完，三处改动：① 打包 —— bundle.resources 收录 docs/compliance/THIRD-PARTY-NOTICES.md，安装后落在资源目录；② 命令 —— third_party_notices 依次找「资源目录」→「仓库生成路径（开发版）」，返回来源/字节数/全文；③ 界面 —— 「关于 / 第三方声明」面板，懒加载（点击才拉，它 1 MB），可滚动全文。**找不到时不说「文件不存在」**：返回的是「在仓库根执行 pwsh tools/license-audit.ps1 -Notices」——空面板只会让人以为软件坏了（单测钉住这条）。**打包前置条件**：没跑过 -Notices 就 tauri build 会因找不到资源失败，这是有意的 —— 宁可打不出包，也不要打出一个没有声明的包。单测 2 项。**还差**：真实安装包验证（只到「资源被收录 + 命令能读到 + 界面能显示」这一层，出包后在干净机器上打开「关于」还没验过）、Android 侧没有对应投放（且 Gradle 依赖还没进清单）。详见 docs/41 §7。' }
    @{ T = '[M5] 第三方组件声明（清单 + 去重许可全文，THIRD-PARTY-NOTICES）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。把「署名/免责文本」的**材料**做出来：pwsh tools/license-audit.ps1 -Notices 生成 docs/compliance/THIRD-PARTY-NOTICES.md（1 MB，平时不生成，发布前才需要）。内容 = 组件清单（按许可原文分组；635 个包剔除 10 个自有 crate = 625 个第三方组件）+ 许可全文（从每个包的 manifest_path 同目录读 LICENSE*/LICENCE*/COPYING*/NOTICE*，按**内容去重** → 324 份）+ 缺全文显式标记（只在 Cargo.toml 写了 SPDX 标识的包标 ⚠️无全文，不假装有）。两个刻意的口径：① **全量**（含构建期依赖）——它是分发包实际内容集的超集，多列不构成合规问题、漏列才是；② **自有 crate 不进第三方声明**（cargo metadata 里 source 为 null 的是本仓库自己的，不是第三方；它们的许可文件在仓库根 LICENSE + NOTICE 里）—— 第一版把它们列进去并标「无全文」是分类错误，已修（635 → 625）。单测 4 项（同文本去重、双许可两份都收且非许可文件不收、无文件包仍列出并标出、声明幂等且组内排序稳定）。**还差**：投放位置（声明躺在仓库 ≠ 用户看得见，放进安装包/关于页是发布流程的一步）、Android Gradle 依赖仍未进清单。详见 docs/41 §6。' }
    @{ T = '[M5] 依赖许可审计（Rust + 前端；CI 护栏 + 自动报告）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（M5 合规清单第一块）。发布前必须回答「这些依赖允许我这样分发吗」，本轮把它做成可重复跑 + 有 CI 护栏的东西：采集在 tools/license-audit.ps1（调 cargo metadata 与 pnpm licenses —— 环境知识），判定与渲染在 audiolink-tools::license（Rust，13 项单测覆盖 OR/AND/WITH、旧式斜杠、括号、未知许可与报告幂等）。判定语义：OR 任一可用即可（选择权在我们，取最宽）、AND 全部必须可用（取最严）、WITH 当原子。三条刻意保守的规则：未知许可进 notice 不进 denied（未知不等于安全也不等于能用）；AND/OR 混用一律进 notice（不做 SPDX 优先级推断）；旧式 MIT/Apache-2.0 按历史约定当 OR。**实测（首次运行）：Rust 635 包 + 前端 88 包，denied 0 / notice 17。** 报告落在 docs/compliance/license-report.md（自动生成、幂等：不含时间戳与路径）。报告暴露的真实待办：uniffi 全家 8 个包是 MPL-2.0（文件级 copyleft —— 可静态链接进闭源产品，但被修改过的 MPL 文件必须公开；我们没改过它的源码，所以当前合规，但这条要进发布检查单）、lightningcss 2 个包 MPL-2.0（只进构建不进产物）、webpki-root-certs 的 CDLA-Permissive-2.0 与 unicode-ident 的混用表达式都进 notice（**没有自动放行，这是对的**）。**没有 GPL/AGPL/SSPL/非商业许可** —— 这是「可以发布」的前提结论，而且可重复验证。CI：desktop job 新增一步 license audit（那里同时有 cargo 与 pnpm），新引入不能分发的依赖会在 CI 里红。未覆盖（诚实）：Android Gradle 依赖、二进制内部第三方库、字体与图标资源；署名/免责文本的实际投放位置是另一件事，还没做。详见 docs/41-compliance-license-audit.md。' }
    @{ T = '[M5] 真实更新流程验证（两版本 + Release 托管 + 验签）'; M = 'M5'; P = 'P1'; S = 'Todo'; B = '本轮把「签得出来」做完了（密钥对 + .sig + latest.json），但**「装得上去」没验**。要验需要三件东西同时在位：① 干净机器装 v0.1.0；② 发布 v0.1.1（含 .sig 与 latest.json，Release 必须能被 releases/latest/download 命中）；③ 客户端检测 → 下载 → 用公钥验签 → 安装 → 重启后版本号变了。顺带要验的：篡改过的安装包必须被**拒绝**（否则验签等于没做）。依赖：CI secrets（TAURI_SIGNING_PRIVATE_KEY）要先配上；本地私钥是开发用的，正式发布前重新生成。 2026-09-17 进展：发布前能自动核对的那一半做完了 —— 新增 tools/check-update.mjs（真 Ed25519 验签）并接进 release.yml，且它第一次运行就抓到「latest.json 比安装包旧 9 小时、签名对不上」这个真缺陷（详见「更新清单与产物同源校验」条目）。剩下的是装上去这一步：需要两个版本 + Release 托管 + 干净机器，属人工/环境项。' }
    @{ T = '[M5] 更新清单与产物同源校验（本地验签 + 发布流程护栏）'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-17 完成。自动更新链路是「读 latest.json → 下载 → 验签 → 安装」，前两步肉眼可查、第三步只有算一遍才知道。新增 tools/check-update.mjs：读清单与 tauri.conf.json 的公钥，对本地安装包做真正的 Ed25519 验签（minisign prehashed 模式，签名对象是 BLAKE2b-512(file)；两种模式都试并报出命中哪种）。为什么用 Node 而不是 PowerShell：Ed25519 与 BLAKE2b-512 都是 Node 内置，而 PowerShell 的 .NET 没有 BLAKE2b、也不保证有 Ed25519。第一次运行就报错：清单里的签名（420 字符 base64）与 .sig 文件（560 字符）不是同一份，时间戳显示清单比产物旧了 9 小时 —— 清单是当初生成的，之后重新构建过安装包（.sig 随之变化）而没人重新生成清单。客户端拿这份清单更新会验签必然失败，用户看到的是一句「签名不匹配」，而真正的原因（清单过期）藏在别处。已用 tools/tauri-latest-json.ps1 重新生成并验签通过。验证（含破坏性）：同源则通过 [prehashed (BLAKE2b-512)]；把安装包改一个字节则失败（证明它真的在验密码学，不是只比字符串）；用过期副本也失败（能区分清单与这个文件是否配套）。已接进 release.yml：生成清单后跑一次，清单过期会让发布流程当场失败，而不是等用户更新失败。' }
    @{ T = '[M5] 自动更新签名链路（密钥对 + 签名打包 + latest.json 清单）'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成（「配置在、功能不可用」这条动掉了）。① pnpm tauri signer generate 生成密钥对（私钥放 ~/.tauri/audiolink.key = **仓库外**，公钥写进 tauri.conf.json）；② createUpdaterArtifacts 打开；③ 带 TAURI_SIGNING_PRIVATE_KEY 打包 → **实际产出 AudioLink_0.1.0_x64-setup.exe.sig**（0.4 KB，minisign 格式）；④ 新增 tools/tauri-latest-json.ps1 生成 updater 要的 latest.json（版本 / URL / 签名，版本取自 tauri.conf.json 单一来源，URL 与 updater.endpoints 同一个地址）。**两个坑**：环境变量名要 TAURI_SIGNING_PRIVATE_KEY（私钥**内容**），用 _PATH 会报「找到了公钥但没有私钥」；**tauri build 缺私钥时先产出安装包再报错** —— 很容易留下一个「看起来打好了、其实更新不可用」的包，清单脚本因此把「找不到 .sig 就抛错」钉死。**仍未验**：真实更新流程（需旧版本 + 新版本 + Release 托管三件同时在位）、CI secrets 未配（需人工）、本地私钥是开发用的（密码 dev-only-change-me，正式发布前重新生成）。详见 docs/42 §5。' }

    @{ T = '[M5] 桌面安装包（NSIS）首次真实产出 + 声明随包就位'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。桌面安装包**首次真实产出**：pnpm tauri:build --bundles nsis → 首次冷编译 5m14s → AudioLink_0.1.0_x64-setup.exe（3.69 MB）。用 7z 直读安装包内容确认两份关键条目都在：audiolink-desktop.exe（15 089 152 B）与 THIRD-PARTY-NOTICES.md（1 031.5 KB）。**第一次打包就抓出一个真缺陷**：bundle.resources 写成数组（["../../docs/compliance/THIRD-PARTY-NOTICES.md"]）时，Tauri 把路径里的 .. 转义成 _up_，安装包内路径变成 _up_/_up_/docs/compliance/THIRD-PARTY-NOTICES.md，而运行时命令找的是 resource_dir()/THIRD-PARTY-NOTICES.md —— 两边对不上，装了包之后「关于」面板必然显示「未找到声明」。改成 map 形式（{ "../../docs/compliance/...": "THIRD-PARTY-NOTICES.md" }）后包内变成根级文件，与运行时查找路径一致（重新打包 + 7z 复验）。**为什么值钱**：光看配置发现不了，只有真的打出包、真的去看包内路径才会暴露。**仍未验**：安装后实读（本项验的是「资源进了包 + 包内路径与运行时一致」，没在干净机器上装完打开「关于」确认真的读出来）、安装包未签名、Android 侧无对应流程。详见 docs/42 §4。' }
    @{ T = '[M5] 绿色版（便携包）：exe + 声明 + 说明 → 带校验和的 zip'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成。路线图 M5 交付物 3 要的是「安装包 + 绿色版 + APK×2 ABI」，前两轮补了后两项，本轮补绿色版：新增 tools/tauri-portable.ps1 —— 把桌面 exe + THIRD-PARTY-NOTICES.md + README-portable.txt 打成一个 zip（5,373.7 KB，exe 14,826 KB 压缩后），并输出 SHA256SUMS.txt。**一个真实的正确性点**：Tauri 的 resource_dir() 在便携形态下就是 exe 所在目录，所以第三方声明必须与 exe 同级 —— 不摆的话「关于 / 第三方声明」面板显示「未找到声明文件」，而那是合规项不是装饰；安装版由 bundle.resources 处理，绿色版得自己摆（脚本注释里写了理由）。配置仍写用户目录 %APPDATA%\com.gotkicry.audiolink，README 写明「设置不跟着 zip 走」，免得用户拷到另一台机器以为丢了。验证：zip 内容逐条核对（三个条目、体积对得上）；-Verify 开关解压到临时目录并**真启动一次**（进程存活 8 s，不是「应该能启动」）；CI 侧 release.yml 的 desktop job 加了打包与收集步骤，产物随 artifact 进 Release（files: dist/**/* 自动带上）。**未验**：window-state.json 的时间戳在本次启动里没变 —— 因为 -Verify 用 Stop-Process -Force 收尾，而窗口状态是正常退出时才写，且 AudioLink 是「关窗不退出」（托盘常驻），无法在不做 GUI 交互的前提下优雅退出；「配置写用户目录」因此按代码事实陈述（app_config_dir()，与安装形态无关）。绿色版也没有代码签名（与安装包同一条待办）。详见 docs/42-m5-release-pipeline.md §10。' }
    @{ T = '[M5] 用户文档：用户手册（中/英）+ 故障排查（中/英）+ CONTRIBUTING.md'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成。路线图 M5 交付物 4 此前完全没做（仓库里连 CONTRIBUTING.md 都没有）。新增 docs/manual/user-guide.zh-CN.md 与 user-guide.en-US.md（两份同构 13 节：装哪个形态、三步配对、推流与接收、Windows 采集、设置、同步组与多源对齐、遥测读数怎么读、配置与数据位置、卸载、许可与第三方声明、以及「还没做的」）、docs/manual/troubleshooting.zh-CN.md 与 troubleshooting.en-US.md（每条都来自真实踩坑：两台设备不在同一网段互 ping 不通、AP 客户端隔离、播放器独占模式导致采不到声音、MIUI 上 adb install -99 要在开发者选项开「USB 安装」、装错 ABI 报「应用未安装」、关窗不退出是设计（托盘常驻）、SmartScreen 未签名、绿色版缺 WebView2、自动更新失败的三个前置条件），以及仓库根 CONTRIBUTING.md（先读顺序、跨端契约纪律、门禁清单（含 cargo fmt --all --check，漏跑过导致 CI 红）、提交信息约定、注释写「为什么」、界面文案走 i18n、纯逻辑优先、诚实记账、护栏要自证、看板同步与远端核对、许可审计）。顺手修掉一个对外缺陷：README.md 第一屏还写着「状态：规划完成，等待开发（v0.1.0 尚未实现）」，而安装包 / 绿色版 / APK 都已产出、CI 全绿；已改为真实状态并加「用户文档」索引表。手册只写已实现的能力，Android 内录与麦克风、Android 自启与省电引导、代码签名都明确列在「还没做的」里。未验：手册里的操作步骤没有逐条在真机上走一遍（需要真机，与 M1/M2 真机验收同一条阻塞）。' }
    @{ T = '[M5] 发布工作流（release.yml）修复与首次真实运行'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。这份 workflow 从仓库骨架提交起就在，**却从未真正跑过**（从没打过 tag）。读一遍发现四个问题：① 产物路径写成 desktop/src-tauri/target/...，而本仓库 .cargo/config.toml 把 target 固定成 x86_64-pc-windows-msvc，产物在仓库根 target/ —— 收集步骤必然空手而归，且 -ErrorAction SilentlyContinue 会把这件事吞掉；② 没有生成第三方声明（桌面安装包要带它，否则打包直接失败）；③ 没有生成 latest.json（自动更新永远停在「配置在、功能不可用」）；④ 缺签名密钥时不给退路。全部修正，并把构建逻辑移进 tools/tauri-build.ps1（在 Actions 的 run 块里做「条件 + 覆盖配置」要过 PowerShell→pnpm→tauri 三层传参，内联 JSON 的引号会被吞掉，CI 实测报 key must be a string）。**首次真实运行（run 35119443752，workflow_dispatch + publish=false）**：desktop installer success 580 s、android apk success 94 s、publish release 正确 skipped；产物核对（gh run download + 7z l 直读）—— AudioLink_0.1.0_x64-setup.exe 3776.5 KB，内含 audiolink-desktop.exe（15 080 448 B）与**根级** THIRD-PARTY-NOTICES.md。**一个值得记住的教训**：我中途把 run: | 行删掉，GitHub 的反应是「workflow 名字退化成文件路径 + 每次 push 都触发 + workflow_dispatch 消失」，而**本地 YAML 解析器照样解析成功** —— 「本地能解析」不等于「GitHub 能接受」，发布工作流必须真的跑一次才算数。' }
    @{ T = '[M5] 发布流程：tag → 构建 → GitHub Release（Release notes + 校验和）'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成（整条链路跑到最后一步）。过程里又发现一个自己的设计缺陷：release job 的条件是「tag 推送 || publish=true」，而创建 Release 用的 tag 取自 GITHUB_REF_NAME —— 手动 dispatch 时那是**分支名**（main），于是会建出一个叫 main 的 Release。修法是让手动路径**必须显式给版本号**（新增 version 输入），并在 job 里先解析 tag（tag 触发用 tag 名，手动触发用 v{version}），解析不出来就 ::error:: 直接失败 —— 宁可这一步红，也不要建出一个名字错误的 Release。**实测（run 35126756341，workflow_dispatch + publish=true + version=0.1.1）**：desktop installer success 612 s、android apk success 112 s、**publish release success 12 s**；建出草稿 Release v0.1.1（**draft=true**），资产两个（AudioLink_0.1.0_x64-setup.exe 3803 KB、app-debug.apk 19 770.2 KB）；**对外不可见**：GET /releases/latest 返回 **404**；**没有打 tag**（git ls-remote --tags 为空）—— 草稿发布不打 tag 是 GitHub 的行为。验证完把测试草稿删掉了，仓库回到没有 Release 的状态。**如实观察**：资产里的 APK 是 app-debug.apk（因为没配 keystore secrets → 走降级分支，符合设计），要出真 release APK 还得配 secrets（已立 [环境] 配置 CI secrets）。剩下一步是**真发布**（把草稿点成正式），那是人工动作。详见 docs/42 §8。' }

    @{ T = '[M5] Android release 打包流水线（assembleRelease + keystore 走 CI secrets）'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。原先的问题是：CI 里没有 keystore secrets，所以 release.yml 里那条 assembleRelease 路径**永远是降级走的**，等于「配置写了但从没跑过」—— 与 release.yml 一开始的状态是同一类毛病。于是本地用**测试 keystore** 把它跑通：keytool -genkeypair（测试用，不入库，.gitignore 已含 *.jks）→ 写 android/keystore.properties（同样不入库）→ gradlew :app:assembleRelease → **BUILD SUCCESSFUL in 1m 34s**。核对：体积 **release 7.84 MB vs debug 19.17 MB（降 59%，R8/minify 确实生效）**；**apksigner verify --print-certs 通过：V2 Signer，证书 CN=AudioLink Test, OU=Dev, O=AudioLink…**；assets\THIRD-PARTY-NOTICES.md（1 056 775 B）在 release APK 里也在。**为什么 7z l 看不到 META-INF/*.RSA 是正常的**：现代 Android 用 APK Signature Scheme **v2**，签名在 zip 结构里而非 META-INF —— 以 apksigner 输出为准。仍未验：CI 侧的真 release 路径（需把 keystore 配进 secrets，人工）、装到真机上跑；测试 keystore 不能用于发布。详见 docs/42 §7。' }
    @{ T = '[M5] 分 ABI 打包：assembleRelease 产出两个包（arm64-v8a / armeabi-v7a）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-17 完成。路线图 M5 交付物 3 写的是「APK×2 ABI」，此前产出的却是**一个 universal 包**（app-release.apk 7.84 MB，同时装 arm64-v8a 与 armeabi-v7a 两份 libaudiolink_ffi.so 加两份 libjnidispatch.so）—— 等于每台设备都下载一份永远用不到的本地库。改用 splits.abi（isEnable + reset + include(arm64-v8a, armeabi-v7a) + isUniversalApk = false）：app-arm64-v8a-release.apk 5.21 MB（−33.5%）、app-armeabi-v7a-release.apk 3.84 MB（−51.0%）；两个包都用 apksigner verify --print-certs 验过 V2 Signer（CN=AudioLink Test），并用 zip 目录逐条核对「arm64 包只含 lib/arm64-v8a/*、v7a 包只含 lib/armeabi-v7a/*」（各 4 个 .so）；debug 变体同样分 ABI（16.54 / 15.17 MB，原 19.17 MB）。**踩到一个真缺陷**：ABI 列表先被写在 defaultConfig.ndk.abiFilters 与 splits.abi.include 两处，AGP 直接以 Conflicting configuration ... cannot be present when splits abi filters are set 拒绝 —— 现在 ABI 只在 splits.abi.include 声明一处，ndk { abiFilters } 整块删掉。顺带给 android/scripts/build-rust.ps1 补护栏：清理不属于本次 -Abi 的旧 ABI 产物（残留 .so 会被打包挡在包外，却让人误以为那个 ABI 还在支持）。支持集合保持 FR-40 的 arm64-v8a + armeabi-v7a 不变：本轮最初按常识假设成 x86_64，读到 docs/01 FR-40 后全部回退 —— 需求文档是契约，既不该凭「现代设备都是 arm64」收窄，也不该凭「模拟器方便」扩张。发布侧无需改动：release.yml 的收集步骤本来就是 find android/app/build/outputs/apk -name *.apk，下次 tag 发布两个包会一起进 Release 资产。仍未验：两个包装到真机跑一遍（与 M1/M2 真机验收同一条阻塞）。详见 docs/42-m5-release-pipeline.md §9。' }
    @{ T = '[环境] 配置 CI secrets（Tauri 更新签名 + Android keystore）'; M = 'M0'; P = 'P1'; S = 'Todo'; B = '2026-09-16 立。两条发布链路现在都「代码就绪、只差密钥」，而密钥进 CI 是**人工操作**（仓库 Settings → Secrets），代码改不了 —— 所以单独立一条，免得发布前一天才发现。要配的：① TAURI_SIGNING_PRIVATE_KEY（私钥内容）+ TAURI_SIGNING_PRIVATE_KEY_PASSWORD —— 配上之后 desktop job 会自动从「降级构建」切到「签名 + 生成 latest.json」；② ANDROID_KEYSTORE_BASE64 + ANDROID_STORE_PASSWORD + ANDROID_KEY_ALIAS + ANDROID_KEY_PASSWORD —— 配上之后 android job 会走 assembleRelease（本地已用测试 keystore 验证该路径可通，见 docs/42 §7）。**验收判据**：跑一次 release workflow，日志里不再出现那两条 ::warning::，且产物里有 .sig 与签名有效的 release APK。**注意**：本地那个测试 keystore 不能用于发布，正式密钥要重新生成并妥善保管 —— 密钥丢了就签不出更新包。' }


    @{ T = '[M5] Windows 代码签名证书（外部资产，发布前人工准备）'; M = 'M5'; P = 'P2'; S = 'Todo'; B = '盘点发现（docs/42 §2.2）：未签名的安装包会触发 SmartScreen 警告。代码签名证书是**外部资产**（要购买、要实名），不是代码能解决的 —— 只能诚实标注为「发布前需人工准备」，列在这里免得发布前一天才发现。' }
    @{ T = '[M5] Android 依赖进许可清单（Gradle 树 + POM 许可 + 判定）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成（原 Todo 里「Gradle 依赖进清单」这一半）。采集依赖坐标用 gradlew :app:dependencies --configuration releaseRuntimeClasspath 的依赖树（不引第三方 Gradle 许可插件 —— 那要往构建里再塞一个供应链依赖还要联网），许可从 Gradle 缓存里每个 POM 的 <licenses> 节点读（完全离线），规范化与判定在 audiolink-tools::license（Rust，可单测）。**实测：Android 114 个组件，allowed 113 / notice 1 / denied 0**；那一条 notice 是 com.google.guava:listenablefuture 1.0 —— 它的 POM 没有声明任何许可（空壳 POM，真许可由 guava 本体覆盖），进 notice 而不是 allowed 正是「未知不等于安全」在起作用。许可分布：110 个 The Apache Software License, Version 2.0 + 10 个 Apache-2.0 + 1 个 BSD-3-Clause + 1 个 LGPL-2.1-or-later OR Apache-2.0（JNA 双许可 → OR 取最宽 → allowed）+ 1 条未声明。两个细节：**规范化顺序有语义**（lesser general public license 必须排在 general public license 之前，否则 LGPL 会被误判成 GPL —— 一个可分发一个不可分发，有单测钉住）；**(c) 是版本约束不是依赖**（把它当依赖会让组件数虚高）。新增 tools/android-licenses.ps1（采集）+ license-audit --android（判定）。详见 docs/41 §8。' }
    @{ T = '[M5] Android 侧声明投放（应用内「开源许可」入口）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。① 打进包：license-audit.ps1 -Notices 生成后同步一份到 android/app/src/main/assets/（**只有一个生成源** —— 手工复制迟早会漂移）；② 读取：NoticesLoader.fromText(...) 是**纯函数**（读 assets 需要 Context，但真正要钉住的是「找不到怎么办」这条只在打包漏资源时才走到的规则，所以三条单测全在纯 JVM 上跑，并覆盖了「空文件与没有文件是同一件事」）；③ 界面：LicensesScreen（Compose，可滚动），入口是主界面顶栏的「开源许可」；④ 找不到时与桌面端同一条规则：**说清怎么生成**，不显示空白页。**实测**：gradlew :app:testDebugUnitTest :app:assembleDebug → BUILD SUCCESSFUL in 55s；NoticesLoaderTest 3 项通过（连同 9 个既有测试类共 76 项全绿）；7z l app-debug.apk 直读 → **assets\THIRD-PARTY-NOTICES.md（1 056 775 B，压缩后 179 045 B）**；APK 19.17 MB。**仍未验**：真机上点开「开源许可」实际渲染（本项验的是「资源进了 APK + 逻辑单测通过」）；Android 许可审计仍未进 CI；两端提示语常量各自维护。详见 docs/41 §9。' }


    @{ T = '[M5] 桌面常驻：托盘菜单 + 关窗隐藏 + 退出时优雅收尾'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-16 完成。做掉 lib.rs 里两条 TODO(M5) 并补上自启入口：① **关窗 ≠ 退出**（CloseRequested 里 prevent_close + hide —— AudioLink 是后台常驻的音频工具，关掉窗口不代表用户想停掉正在播放的音频）；② **托盘菜单**（显示主窗口 / 退出；左键唤出窗口、右键出菜单 —— 窗口藏起来之后托盘是唯一能叫回窗口和真正退出的地方）；③ **退出前优雅收尾**（quit_app 先 engine.shutdown() 再 exit(0) —— 这条最容易一直没人管，而代价落在对端身上：对方要多等一次 QUIC 空闲超时才能判掉会话；桥接层内部有 3 s 上限，超时就超时，照样退出但留一行 stderr）；④ **开机自启开关**（autostart_enabled / set_autostart，插件早就注册了却没有入口）。两个刻意的细节：退出路径带 3 秒上限（不能因为对端没响应卡住用户）；自启状态从**系统**读（autolaunch().is_enabled()），不本地记一个布尔 —— 用户在系统设置里改过之后这里必须显示真实状态。顺手清掉一处重复定义：tauri.conf.json 里原本有 app.trayIcon 配置，与 Rust 侧新建的托盘同 id，已删配置那份，图标改取 default_window_icon()。**实测**：cargo check 通过（含 generate_context 的编译期配置校验）、cargo test -p audiolink-desktop 23 项通过、pnpm build 通过、pwsh tools/tauri-build.ps1 release 打包成功（AudioLink_0.1.0_x64-setup.exe 3793.5 KB + .sig），7z 直读安装包含 audiolink-desktop.exe（15 181 824 B）+ 根级 THIRD-PARTY-NOTICES.md。**没验**：托盘图标显示/左键唤出/右键菜单、关窗后进程仍存活、退出时对端真的收到 BYE（引擎侧优雅关闭本有 e2e，本轮接的是托盘/窗口这条调用路径）、自启在系统里的实际效果 —— 都需要真机 GUI 会话。详见 docs/43-m5-desktop-shell.md。' }
    @{ T = '[M5] 桌面端中英双语（i18n + 全部界面文案）'; M = 'M5'; P = 'P1'; S = 'Done'; B = '2026-09-17 完成。此前界面文案全散在 JSX 里写死中文，本轮做成「一张表 + 一个函数」：新增 desktop/src/i18n.ts —— zh 表 139 条（as const 定义键集合）+ en 表声明为 Record<MessageKey, string>（英文漏一条 tsc 就红）、模块级 t(key, vars) 与 useLocale()（useSyncExternalStore 订阅，语言一变 App 重渲染，t 是渲染期求值所以整棵树跟着换）、语言偏好走 settings.json 的 locale 键（新命令 locale / set_locale，只接受 zh-CN / en-US，切换顺序先立即生效再落盘）。18 个文件；可机械化部分（字符串字面量 / JSX 属性 / 单独成行的文本节点）用脚本按「中文原文 → 键」一次替换 —— 字典即映射表，不另维护对照表；13 处模板串与混合节点手工改。残留中文 UI 文案 0。**两个真缺陷**：① PEER_STATE_LABEL 与 VERDICT_TEXT 原本是模块级常量 —— 常量只在模块加载那一刻求值，语言切换后整个界面都变了只有这几个字不动，且不报错不崩溃；已改成函数并写明理由。② TelemetryPanel 里 const t = telemetry 这个短别名把翻译函数遮蔽了，翻译调用于是被解析成「调用一个遥测对象」，改名 tele 才过。**新增护栏** desktop/scripts/check-i18n.mjs 并接进 pnpm build：键集合 + 占位符集合 + 空文案三项（tsc 管不了占位符，英文漏写 {name} 会静默少一个值），破坏性验证：去掉 en 的 {name} → exit 1，恢复 → exit 0。验证：pnpm build 通过（36 modules）、残留扫描 0、clippy 零警告、desktop 测试通过。**未验**：没有真实 GUI 会话实际切换语言看观感（中英文案长度差异导致的换行与按钮宽度未看）；Android 侧仍单语言（values-en/ 未做，路线图 M5 双语只写在桌面交付物里）。详见 docs/45-m5-bilingual.md。' }
    @{ T = '[M5] 启动时自动连接上次设备（FR-31）'; M = 'M5'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。常驻 + 自启 + 自动重连三件凑齐才是「开机就能用」，这是第三件。① 记住设备：只有 connect **成功**才写 last_peer（失败也记的话，开机就会去连一个已知连不上的地址）；② 该不该连：AutoConnectPolicy::target() —— **开关打开且确实有记录**才返回目标；③ 启动时：前端挂载后调一次 try_auto_connect；④ 失败怎么办：**静默**返回 null —— 用户什么都没点，不该在开机时弹「连不上」的错误横幅。**一条刻意的边界**：target() 只认「上次那台设备」，不做「扫描一遍、连第一个看到的设备」那类事 —— 那等于在用户没要求的情况下连到别人的机器上；空字符串也按「没有记录」处理，否则存储被写坏时会变成「连本机任意端口」这种怪行为（两条都有单测，settings.rs 共 4 项）。设置持久化用 tauri-plugin-store（插件早就注册了却一直没用）。**实测**：cargo test -p audiolink-desktop 27 项通过（新增 4 项）、pnpm build 通过、全量内核门禁 fmt/clippy/437 项测试全绿。**没验**：真实启动流程里的自动重连（需要「曾经连过、现在开机」的真实场景 + GUI 会话），以及与手工连接之间的并发（都调 connect，外壳侧有去重判据但没在真机压过）。详见 docs/43 §4。' }

    @{ T = '[M5] 产品化：托盘/自启/自动更新/双语/双 ABI 发布/合规清单'; M = 'M5'; P = 'P3'; S = 'In Progress'; B = 'docs/05-roadmap.md M5。2026-09-17：双 ABI 发布这一半落地 —— assembleRelease 产出两个按 ABI 的包（arm64-v8a 5.21 MB / armeabi-v7a 3.84 MB，均 V2 签名有效），详见「分 ABI 打包」条目与 docs/42 §9。2026-09-17：桌面端中英双语也落地了（139 条文案 × 2 语言 + i18n 护栏，详见「桌面端中英双语」条目）。2026-09-17：绿色版也落地了（便携 zip 5.37 MB + SHA256，-Verify 真启动过）。2026-09-17：用户文档也齐了（用户手册与故障排查各中英两份 + CONTRIBUTING.md），并顺手修正了 README 里过时的「尚未实现」状态行。至此 M5 交付物只剩「真机安装验收」仍受阻（另有代码签名证书这条外部资产待办）。' }

    # ---- 技术债与护栏 ----
    @{ T = '[护栏] 「定长载荷自洽」测试：LEN == 字段宽度之和'; M = 'M0'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。长度常量改为「最后一个字段偏移 + 字段宽度」算式（新增 U8/U16/U32/U64/I64_LEN 与 CLOCK_* 偏移常量），DATAGRAM_HEADER_LEN / CONTROL_HEADER_LEN 同源；Ptype::payload_len_rule()、ClockProbe/ClockReply::LEN、NACK_MAX_ITEMS 及编解码偏移全部引用同一批常量，定长拒绝消息由常量拼出（不再手抄）。新增 audiolink-proto/tests/payload_len_table.rs：§3 载荷表的独立副本（帧头 7 字段 / CLOCK_PROBE 2 / CLOCK_REPLY 4 / 控制帧头 4），断言常量 == 表值、实际编码长度 == 宽度之和、按表累加偏移读回哨兵字段、规则表与编码器一致（len±1 被拒、0 项 / max+1 项 / 非 4 倍数被拒、Opaque 吃到 MTU 上限）、ptype 表自洽；9 项用例。破坏性验证三组：LEN 漏一个 i64 → 3 用例红；规则表写死 24 → 3 用例红；解码侧 t2 偏移漂移 → 1 用例红。线上字节不变（帧头 24 / 控制头 8 / 载荷 12 与 28）。详见 docs/20-guards-and-tooling.md。提交 6419333；CI run 35069992337（core / android / desktop / version-consistency）全绿。' }
    @{ T = '[文档] docs/10-handoff.md 状态更新（M0 已完成）'; M = 'M0'; P = 'P2'; S = 'Done'; B = '已更新：M0 全绿 + M1 三项 P0 完成、实测基线、下一步为 M1 主线（QUIC/Android 播放/最小 UI）' }
    @{ T = '[安全] docs/06-dev-environment.md 本机路径脱敏'; M = 'M0'; P = 'P2'; S = 'Done'; B = '2026-09-16 完成。docs/ 下 7 个文件（06/10/11/12/14/15/16）的本机绝对路径全部换成占位符：%LOCALAPPDATA%\Android\Sdk、<JDK 17 根目录>、<Android SDK 根目录>、<你的 keystore 路径>、<本机用户目录>（含 local.properties 的 sdk.dir / storeFile 转义写法）。docs/06 §1 顶部新增占位符对照表：含义 + 怎么查本机实际值 + 命令示例替换方式（占位符连同单引号一起替换即可执行）。验证：全仓搜开发机用户名 0 命中，tools/ 示例原本已是 <你> 占位符。详见 docs/20-guards-and-tooling.md §2。提交 2a01879；CI run 35069992337 全绿。' }
    @{ T = '[护栏] 跨端一致性夹具：同一组 golden vectors 在 Rust 与 FFI 双跑'; M = 'M1'; P = 'P3'; S = 'Done'; B = 'audiolink-ffi::protocolSelfTest()：FFI 侧自带 §12 三组向量（解码→字段→再编码逐字节一致），并把 audiolink-proto 的 tests/golden_vectors.rs 原文 include_str! 进来**运行期逐字节比对**四份常量 —— 上游一改向量就红灯（该守卫当场抓到过一次解析注释的 bug）。18 测试绿' }
    @{ T = '[工具] alp2-dump 支持 pcap/pcapng 输入'; M = 'M1'; P = 'P3'; S = 'Done'; B = '2026-09-16 完成。输入按内容自动分派：4 字节 magic 命中 pcap/pcapng 走抓包分支，其余仍按 hex 文本（原行为不变）；新增 --pcap（强制抓包分支）、--port N（默认 58290，§1 的 QUIC 端口）、--all-ports。新增 audiolink-tools::pcap（不引第三方抓包库）：pcap 四种 magic（µs/ns × 大小端）、pcapng 的 SHB(byte-order magic 定端序)/IDB/EPB/SPB（块长 4 字节对齐且块尾副本必须等于块头）、链路层 Ethernet(含 802.1Q/802.1ad VLAN 标签链)/Linux SLL v1/raw IP/BSD loopback、IPv4(IHL)/IPv6(固定 40 B)、udp_len<8（GSO）按剩余字节；不做 IP 分片重组 / IPv6 扩展头链 / 隧道解封装（判为非目标包跳过）。剥不出 UDP 计「跳过」而非解码失败。回归：core/crates/audiolink-tools/tests/pcap_extract.rs 9 项（夹具现场按 RFC 逐字节合成）：pcap 与 pcapng 端到端剥出 §12 向量再交给 L1 解码、纳秒时间戳换算、双层 VLAN、IPv6 与 Linux SLL、ICMP/未知链路/扩展头跳过、udp_len=0 回退、坏输入全部 Err 无 panic、hex 文本不误判。端到端实测：pcap 与 pcapng 各 2 个目标报文解码成功、跳过 2 个非目标包、退出码 0；--all-ports 时 DNS 包计入失败（端口过滤要挡的噪声）；hex 路径回归通过。详见 docs/20-guards-and-tooling.md §3。提交 402636f；CI run 35069992337 全绿。' }
    @{ T = '[工具] self-loop 支持真机链路端到端测量'; M = 'M1'; P = 'P2'; S = 'Done'; B = '**已实现**：§6 时钟同步接进引擎后，跨机测量由新增的 tools/device-link 承担（PC 侧连真机、PIN 配对、推流、逐项标 [实测]/[模型]/[未测] 的延迟账本），latency-probe 也已能打生产端点（补了客户端证书）。历史背景：**曾被 tools/link-loop 部分取代**：link-loop 用两个真实 Engine 走真 QUIC，按 seq 配对探针量「帧封口→sink 写出」，PC↔PC 段已实测（P50 40.2 ms）。**跨机仍缺**：探针直接比较 Instant，跨机不可相减 —— 需要接 §6 时钟同步（ClockEstimator 已实现并单测，但引擎侧一根线没接，clock_offset_us 恒为 0）' }
    @{ T = '[CI] QUIC 依赖 feature 门控（回收 core job 的 ~2.5 min）'; M = 'M0'; P = 'P3'; S = 'Done'; B = '2026-09-16 实测证伪前提，已按实测处置。core job 4.0 min = test 139 s + rust-cache 恢复 53 s + clippy 25 s；rust-cache 日志 full match，test 步骤的 Compiling 只有 9 个 workspace 本地 crate，quinn/rustls/tokio 一行都没有，即依赖整棵树被 cache 完整复原、不在关键路径上。所以「tools 引入 quinn 后 core 由 1m36s 涨到 4m10s」是引入当天的一次性冷编译；feature 门控在这里没有可回收的时间，而 core 的 clippy 必须保留 --all-features 的 lint 覆盖（把 QUIC 藏进 feature 只会多出没被 lint 的组合）。test 的 139 s 里真正的测试运行只有 39.2 s，其余是 9 个 crate 编译加每个 target 链一个测试二进制。于是把刀口对准编译：5 个无 #[test] 的 tools bin 标 test = false（device-link 与 self-loop 里有测试、原样保留），core 的 test 步骤加 --lib --tests 跳过 9 个全 0 项 doctest；测试零损失（355 项不变，41 降到 27 个 suite）。诚实结论：这两项削减的收益小于 run 间波动（test 139 / 138 / 167 s），core 没有可测回收；进一步压只能拆并行 job，见 docs/26-ci-key-path.md §6。提交 6ae748b / b7e737f；CI run 35080728329 / 35081356931 四个 job 全绿。' }
    @{ T = '[工具] soak-runner（8 h 回环 + 指标采集 + 异常快照）'; M = 'M2'; P = 'P3'; S = 'Done'; B = '2026-09-16 完成。新增 audiolink-tools::soak（判定 + 报告，纯逻辑可单测）与 --bin soak-runner：同一进程起两个真实 Engine（node-a 发送 / node-b 接收），走 127.0.0.1 真实 QUIC 并实跑 §5 PIN 配对；合成源 + NullPlayout，不出声不采声卡，可无人值守长跑。每 1 s 采接收侧遥测，越界即留异常快照（时刻 + 种类 + 当时完整遥测）：not_streaming / underrun / playout_concealment / packet_loss / late_drop / nack_retransmit / bitrate_out_of_range / stalled（连续 5 次零码率）；快照上限 200 条（超出计 dropped_violations），另存每 60 s 一条粗采样（8 h 约 480 条）。默认 8 h（--seconds 28800），预热 3 s 不判，目标码率默认 320000（双发后期望）±30%。报告 JSON 手写字段（不把 serde feature 拉进内核依赖图）。退出码即判定：0 无异常 / 1 有异常 / 2 用法错误。实测：20 s 冒烟 exit 0，码率 312→321 kbps 收敛后稳定、丢包/欠载/掩盖/迟到/NACK 全 0、队列 20 ms、RTT 1.8 ms，报告 750 B；把 --expected-bps 写错 → 6 条 bitrate_out_of_range、exit 1（判定链路闭环）。8 项单测。真正的 8 h 长跑尚未执行。提交 be52681；CI run 35072898528（core / android / desktop / version-consistency）全绿。详见 docs/22-m2-soak-runner.md。（读 JSON 报告，输出违规按类聚合、首次与末次秒数、终值遥测与人话判定；退出码 0/1/2 与 soak-runner 同口径，-Json 供 CI 与看板回填），四个夹具自测（smoke exit 0 / negative exit 1 / 缺失路径 exit 2 / 非 JSON exit 2）。报告新增 violations_total、violations_by_kind、last_violation_at_secs、last_violation_kind、violation_limit_per_kind，旧报告仍可解析。提交 fc05568 与 de21d0b；详见 docs/22 §8-9。 2026-09-17 新增 tools/soak-report.ps1 作为离线判定通路' }
    @{ T = '[CI] Android job：预编译 cargo-ndk（省 ~2 min）'; M = 'M0'; P = 'P3'; S = 'Done'; B = '2026-09-16 实测证伪前提，并顺手把真正的 2 分钟拿回来了。cargo install cargo-ndk --locked 实测只花 1 s：Swatinem/rust-cache 默认缓存 ~/.cargo/bin，二进制早就在 cache 里，所以「每次 run 重编 cargo-ndk」不成立、无需预编译。android job 的真关键路径是 Gradle assembleDebug（130 s）。改为 actions/cache 缓存 ~/.gradle 的 caches 与 wrapper：首轮 miss（0.0 s），次轮命中（6 s）后 android job 192 降到 85 s、assembleDebug 130 降到 16 s，回收 107 s。提交 6ae748b；CI run 35081356931 四个 job 全绿。详见 docs/26-ci-key-path.md。' }
    @{ T = '[CI] core job 反馈时间：拆并行 job（快内核 + 重内核）'; M = 'M0'; P = 'P3'; S = 'Done'; B = '2026-09-16 完成。core 拆成两个并行 job：core-light（types/proto/identity，fmt + clippy + test）与 core-heavy（--workspace --exclude audiolink-desktop --exclude 三个轻内核）。重 job 用 --exclude 而不是逐个 -p：将来新增 crate 会自动落进重 job，不会悄悄漏测（本地用 cargo metadata 校验集合：非桌面成员 9 个 = 轻 3 + 重 6，交集为空）。稳态实测（第二次运行 35098695833，五个 job 全绿）：core-light 80 s（cache 34 / fmt 2 / clippy 7 / test 13），core-heavy 297 s（cache 32 / clippy 19 / test 229）。协议层（golden vectors）拿到结论的时间从 236–256 s 压到 80 s（−69%），代价是墙钟 236–256 s → 297 s（+20%，重 job 多付一份 rust-cache 恢复 32 s 与 checkout）—— 这笔交易是按「协议是跨端契约、改错要三端齐改」立的。冷缓存的成本也记了账：首次运行 35097376811 墙钟 744 s（两个新 job 各自重建依赖树，clippy 295 + test 354），拆 job 的真实成本不是脚本行数，而是缓存被切碎后的第一次运行。详见 docs/26-ci-key-path.md §7-8。' }
    @{ T = '[CI] core-heavy 的 test 步骤：原以为链接是主体，实测是 cargo test 逐个二进制串行（已用 nextest 落地）'; M = 'M0'; P = 'P3'; S = 'Done'; B = '2026-09-16 完成。**本条原始前提（「27 个测试二进制链接是主体」）已被实测证伪**：从 CI 日志逐 suite 取 finished in，26 个 suite 运行时间之和只有 75.8 s、最长单个 16.25 s，所以 core-heavy 的 229 s 里约 153 s 是编译；本地单独量一个空的 engine 测试二进制（编译 + 链接）只要 0.75 s —— 链接从来不是杠杆。真正的浪费是 cargo test 一次只跑一个二进制（26 个互不依赖的二进制排队）。改用 cargo nextest 跨二进制并行：本地热缓存 heavy 集 78.2 s → 21.3 s（连跑三次 18.8/18.8/18.8 s，344 项全过零 flaky；逐项核对无漏测 —— cargo test 报 26 suite/344 passed，nextest 报 344 passed）；CI 上 core-heavy 的 test 步骤 229 → 187 s（−42 s）。**第二次被证伪的是我自己写的推测**：「rust-cache 的 bin 缓存会留住 cargo install 的产物」不成立 —— 四次运行安装步骤都是 375~404 s，一次都没降；改用官方预编译包（get.nexte.st，版本 pin + 装完立刻 --version 校验）后安装步骤 2.0 s。最终稳态（run 35103776301，五个 job 全绿）：core-light 83 s、core-heavy 267 s；协议层拿到结论从 236–256 s 压到 83 s（−66%），墙钟 267 s（+11~31 s）。另加 .config/nextest.toml（单个测试 60 s 告警、fail-fast=false）。详见 docs/26-ci-key-path.md §9。' }

)

$STATUS_OPTIONS = @('Todo', 'In Progress', 'Done')
$MILESTONE_OPTIONS = @('M0', 'M1', 'M2', 'M3', 'M4', 'M5')
$PRIORITY_OPTIONS = @('P0', 'P1', 'P2', 'P3')

# ---------------------------------------------------------------------------
# 辅助
# ---------------------------------------------------------------------------

function Invoke-Gh {
    param([Parameter(Mandatory)][string[]]$Arguments, [switch]$AsJson)
    $output = & gh @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "gh $($Arguments -join ' ') 失败：`n$($output | Out-String)"
    }
    if ($AsJson) {
        return (($output | Out-String).Trim() | ConvertFrom-Json)
    }
    return $output
}

function Get-ProjectFields {
    param([Parameter(Mandatory)][int]$Number)
    return (Invoke-Gh @('project', 'field-list', "$Number", '--owner', $Owner, '--format', 'json') -AsJson).fields
}

function Ensure-SingleSelectField {
    param([Parameter(Mandatory)][int]$Number, [Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][string[]]$Options)
    $existing = Get-ProjectFields $Number | Where-Object { $_.name -eq $Name } | Select-Object -First 1
    if ($existing) {
        return $existing
    }
    if ($DryRun) {
        Write-Host "  [dry-run] 创建单选字段 '$Name'（选项：$($Options -join ', ')）"
        return $null
    }
    Write-Host "  + 创建单选字段 '$Name'（选项：$($Options -join ', ')）"
    Invoke-Gh @('project', 'field-create', "$Number", '--owner', $Owner, '--name', $Name, '--data-type', 'SINGLE_SELECT', '--single-select-options', ($Options -join ',')) | Out-Null
    return Get-ProjectFields $Number | Where-Object { $_.name -eq $Name } | Select-Object -First 1
}

function Item-Title {
    param($Item)
    if ($Item.title) { return "$($Item.title)" }
    if ($Item.content -and $Item.content.title) { return "$($Item.content.title)" }
    return ''
}

function Item-Body {
    param($Item)
    if ($Item.content -and $Item.content.body) { return "$($Item.content.body)" }
    return ''
}

function Item-IsDraft {
    param($Item)
    return ($Item.content -and "$($Item.content.type)" -eq 'DraftIssue')
}

# 草稿条目的正文要按 **content id**（`DI_...`）改，不是按项目条目 id（`PVTI_...`）——
# 实测 gh 会直接报「ID must be the ID of the draft issue content which is prefixed with DI_」。
function Item-DraftContentId {
    param($Item)
    $id = "$($Item.content.id)"
    if ($id.StartsWith('DI_')) { return $id }
    return ''
}

function Set-SingleSelect {
    param(
        [Parameter(Mandatory)][string]$ItemId,
        [Parameter(Mandatory)][string]$ProjectId,
        [Parameter(Mandatory)]$Field,
        [Parameter(Mandatory)][string]$OptionName,
        [Parameter(Mandatory)][int]$Number
    )
    if (-not $Field) { return }
    $option = $Field.options | Where-Object { $_.name -eq $OptionName } | Select-Object -First 1
    if (-not $option) {
        Write-Warning "字段 '$($Field.name)' 没有选项 '$OptionName'，跳过"
        return
    }
    Invoke-Gh @('project', 'item-edit', '--id', $ItemId, '--project-id', $ProjectId, '--field-id', "$($Field.id)", '--single-select-option-id', "$($option.id)") | Out-Null
}

# ---------------------------------------------------------------------------
# 主流程
# ---------------------------------------------------------------------------

Write-Host "AudioLink 任务看板同步（owner=$Owner, project='$ProjectTitle'$(if ($DryRun) { ', DRY-RUN' }))"

try {
    $projectList = Invoke-Gh @('project', 'list', '--owner', $Owner, '--limit', '100', '--format', 'json') -AsJson
}
catch {
    Write-Error "无法访问 GitHub Projects —— token 缺 scope。请先运行：`n    gh auth refresh -s project`n（交互式，需在浏览器完成授权）`n原始错误：$($_.Exception.Message)"
    exit 1
}

$project = $projectList.projects | Where-Object { $_.title -eq $ProjectTitle } | Select-Object -First 1
if (-not $project) {
    if ($DryRun) {
        Write-Host "  [dry-run] 创建看板 '$ProjectTitle'（并关联仓库 $Repo）"
        Write-Host "  [dry-run] 创建单选项字段：Status($($STATUS_OPTIONS -join '/'))、里程碑($($MILESTONE_OPTIONS -join '/'))、优先级($($PRIORITY_OPTIONS -join '/'))"
        Write-Host "  [dry-run] 将写入 $($Tasks.Count) 个条目："
        foreach ($task in $Tasks) {
            Write-Host ("      - [{0}/{1}/{2}] {3}" -f $task.M, $task.P, $task.S, $task.T)
        }
        exit 0
    }
    Write-Host "  + 创建看板 '$ProjectTitle'"
    Invoke-Gh @('project', 'create', '--owner', $Owner, '--title', $ProjectTitle) | Out-Null
    $projectList = Invoke-Gh @('project', 'list', '--owner', $Owner, '--limit', '100', '--format', 'json') -AsJson
    $project = $projectList.projects | Where-Object { $_.title -eq $ProjectTitle } | Select-Object -First 1
}
if (-not $project) {
    throw "看板创建后仍未找到（owner=$Owner, title=$ProjectTitle）"
}

$number = [int]$project.number
$projectId = "$($project.id)"
Write-Host "  看板：$($project.url)（number=$number）"

if (-not $NoLink -and -not $DryRun) {
    Invoke-Gh @('project', 'link', "$number", '--owner', $Owner, '--repo', $Repo) | Out-Null
    Write-Host "  已关联仓库 $Repo"
}

$statusField = Ensure-SingleSelectField -Number $number -Name 'Status' -Options $STATUS_OPTIONS
$milestoneField = Ensure-SingleSelectField -Number $number -Name '里程碑' -Options $MILESTONE_OPTIONS
$priorityField = Ensure-SingleSelectField -Number $number -Name '优先级' -Options $PRIORITY_OPTIONS

# 即使 dry-run 也要真的读一次现有条目 —— `project item-list` 是只读命令。
#
# 不读的后果（2026-09-14 实测暴露）：dry-run 里 `$existing` 恒为空，
# 于是「已存在 / 新建」的预览**全都是「新建」**。而本脚本唯一的危险动作恰恰是
# **造重复条目**（标题是幂等键，靠 `$existing` 匹配）—— 一个分不清重复的预览等于没有预览，
# 会让人误以为「一切都要新建」而去关掉 dry-run 直接跑。
$items = (Invoke-Gh @('project', 'item-list', "$number", '--owner', $Owner, '--limit', '200', '--format', 'json') -AsJson).items
$existing = @{}
foreach ($item in $items) {
    $title = Item-Title $item
    if ($title) { $existing[$title] = $item }
}
Write-Host "  现有条目 $($existing.Count) 个，任务表 $($Tasks.Count) 个"

$created = 0
$updated = 0
$bodies = 0
$unchanged = 0

foreach ($task in $Tasks) {
    if ($DryRun) {
        $mark = if ($existing.ContainsKey($task.T)) { '已存在' } else { '新建' }
        Write-Host ("  [dry-run] {0,-4} [{1}/{2}/{3}] {4}" -f $mark, $task.M, $task.P, $task.S, $task.T)
        continue
    }

    $item = $existing[$task.T]
    if (-not $item) {
        $createdItem = Invoke-Gh @('project', 'item-create', "$number", '--owner', $Owner, '--title', $task.T, '--body', $task.B, '--format', 'json') -AsJson
        $itemId = "$($createdItem.id)"
        Set-SingleSelect -ItemId $itemId -ProjectId $projectId -Field $statusField -OptionName $task.S -Number $number
        Set-SingleSelect -ItemId $itemId -ProjectId $projectId -Field $milestoneField -OptionName $task.M -Number $number
        Set-SingleSelect -ItemId $itemId -ProjectId $projectId -Field $priorityField -OptionName $task.P -Number $number
        $created++
        Write-Host ("  + [{0}/{1}/{2}] {3}" -f $task.M, $task.P, $task.S, $task.T)
        continue
    }

    $itemId = "$($item.id)"
    $statusChanged = "$($item.status)" -ne $task.S
    # 说明（body）也要跟着文档走：看板是文档的机械映射，正文里往往写着口径修正与实测结论
    $bodyChanged = (Item-IsDraft $item) -and ((Item-Body $item) -ne $task.B)
    if ($statusChanged) {
        Set-SingleSelect -ItemId $itemId -ProjectId $projectId -Field $statusField -OptionName $task.S -Number $number
        $updated++
        Write-Host ("  ~ 状态 {0} → {1}：{2}" -f $item.status, $task.S, $task.T)
    }
    if ($bodyChanged) {
        $contentId = Item-DraftContentId $item
        if ($contentId) {
            Invoke-Gh @('project', 'item-edit', '--id', $contentId, '--body', $task.B) | Out-Null
            $bodies++
            Write-Host ("  ~ 说明更新：{0}" -f $task.T)
        }
        else {
            Write-Warning "条目 '$($task.T)' 不是草稿条目，跳过说明更新"
        }
    }
    if (-not $statusChanged -and -not $bodyChanged) {
        $unchanged++
    }
}

Write-Host ""
if ($DryRun) {
    Write-Host "DRY-RUN 结束（没有做任何变更）。去掉 -DryRun 即真正同步。"
}
else {
    Write-Host "同步完成：新建 $created，状态更新 $updated，说明更新 $bodies，已是最新 $unchanged。"
    Write-Host "看板：$($project.url)"
}
