// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package com.gotkicry.audiolink.core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import kotlin.coroutines.resume
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.DelicateCoroutinesApi
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_audiolink_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_audiolink_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "audiolink_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfacePcmFeedMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`samples`: RustBuffer.ByValue,`frames`: Int,`uniffiOutReturn`: IntByReference,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfacePcmPullMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`maxSamples`: Int,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("feedPcm", "uniffiFree")
internal open class UniffiVTableCallbackInterfacePcmFeed(
    @JvmField internal var `feedPcm`: UniffiCallbackInterfacePcmFeedMethod0? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `feedPcm`: UniffiCallbackInterfacePcmFeedMethod0? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfacePcmFeed(`feedPcm`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfacePcmFeed) {
        `feedPcm` = other.`feedPcm`
        `uniffiFree` = other.`uniffiFree`
    }

}
@Structure.FieldOrder("readPcm", "uniffiFree")
internal open class UniffiVTableCallbackInterfacePcmPull(
    @JvmField internal var `readPcm`: UniffiCallbackInterfacePcmPullMethod0? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `readPcm`: UniffiCallbackInterfacePcmPullMethod0? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfacePcmPull(`readPcm`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfacePcmPull) {
        `readPcm` = other.`readPcm`
        `uniffiFree` = other.`uniffiFree`
    }

}




















































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_audiolink_ffi_checksum_func_connect(
): Short
fun uniffi_audiolink_ffi_checksum_func_displayed_pin(
): Short
fun uniffi_audiolink_ffi_checksum_func_engine_start(
): Short
fun uniffi_audiolink_ffi_checksum_func_engine_stop(
): Short
fun uniffi_audiolink_ffi_checksum_func_local_status(
): Short
fun uniffi_audiolink_ffi_checksum_func_peers(
): Short
fun uniffi_audiolink_ffi_checksum_func_protocol_self_test(
): Short
fun uniffi_audiolink_ffi_checksum_func_start_send(
): Short
fun uniffi_audiolink_ffi_checksum_func_stop_send(
): Short
fun uniffi_audiolink_ffi_checksum_func_submit_pin(
): Short
fun uniffi_audiolink_ffi_checksum_func_telemetry(
): Short
fun uniffi_audiolink_ffi_checksum_method_pcmfeed_feed_pcm(
): Short
fun uniffi_audiolink_ffi_checksum_method_pcmpull_read_pcm(
): Short
fun ffi_audiolink_ffi_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "audiolink_ffi"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            uniffiCallbackInterfacePcmFeed.register(lib)
            uniffiCallbackInterfacePcmPull.register(lib)
            // Loading of library with integrity check done.
            lib
        }
        
    }

    // FFI functions
    fun uniffi_audiolink_ffi_fn_init_callback_vtable_pcmfeed(`vtable`: UniffiVTableCallbackInterfacePcmFeed,
): Unit
fun uniffi_audiolink_ffi_fn_init_callback_vtable_pcmpull(`vtable`: UniffiVTableCallbackInterfacePcmPull,
): Unit
fun uniffi_audiolink_ffi_fn_func_connect(`addr`: RustBuffer.ByValue,
): Long
fun uniffi_audiolink_ffi_fn_func_displayed_pin(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_audiolink_ffi_fn_func_engine_start(`config`: RustBuffer.ByValue,`playout`: RustBuffer.ByValue,`capture`: RustBuffer.ByValue,
): Long
fun uniffi_audiolink_ffi_fn_func_engine_stop(
): Long
fun uniffi_audiolink_ffi_fn_func_local_status(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_audiolink_ffi_fn_func_peers(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_audiolink_ffi_fn_func_protocol_self_test(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_audiolink_ffi_fn_func_start_send(
): Long
fun uniffi_audiolink_ffi_fn_func_stop_send(
): Long
fun uniffi_audiolink_ffi_fn_func_submit_pin(`pin`: RustBuffer.ByValue,
): Long
fun uniffi_audiolink_ffi_fn_func_telemetry(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_audiolink_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_audiolink_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_audiolink_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_audiolink_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_audiolink_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_audiolink_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_audiolink_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_audiolink_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_audiolink_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_audiolink_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_audiolink_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_audiolink_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_audiolink_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_audiolink_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_audiolink_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_audiolink_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_audiolink_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_audiolink_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_audiolink_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_audiolink_ffi_checksum_func_connect() != 12465.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_displayed_pin() != 17789.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_engine_start() != 32272.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_engine_stop() != 39110.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_local_status() != 21978.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_peers() != 50122.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_protocol_self_test() != 3293.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_start_send() != 53400.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_stop_send() != 5031.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_submit_pin() != 52703.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_func_telemetry() != 3439.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_method_pcmfeed_feed_pcm() != 1438.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_audiolink_ffi_checksum_method_pcmpull_read_pcm() != 57607.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support
// Async return type handlers

internal const val UNIFFI_RUST_FUTURE_POLL_READY = 0.toByte()
internal const val UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1.toByte()

internal val uniffiContinuationHandleMap = UniffiHandleMap<CancellableContinuation<Byte>>()

// FFI type for Rust future continuations
internal object uniffiRustFutureContinuationCallbackImpl: UniffiRustFutureContinuationCallback {
    override fun callback(data: Long, pollResult: Byte) {
        uniffiContinuationHandleMap.remove(data).resume(pollResult)
    }
}

internal suspend fun<T, F, E: kotlin.Exception> uniffiRustCallAsync(
    rustFuture: Long,
    pollFunc: (Long, UniffiRustFutureContinuationCallback, Long) -> Unit,
    completeFunc: (Long, UniffiRustCallStatus) -> F,
    freeFunc: (Long) -> Unit,
    liftFunc: (F) -> T,
    errorHandler: UniffiRustCallStatusErrorHandler<E>
): T {
    try {
        do {
            val pollResult = suspendCancellableCoroutine<Byte> { continuation ->
                pollFunc(
                    rustFuture,
                    uniffiRustFutureContinuationCallbackImpl,
                    uniffiContinuationHandleMap.insert(continuation)
                )
            }
        } while (pollResult != UNIFFI_RUST_FUTURE_POLL_READY);

        return liftFunc(
            uniffiRustCallWithError(errorHandler, { status -> completeFunc(rustFuture, status) })
        )
    } finally {
        freeFunc(rustFuture)
    }
}

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * `engineStart` 的入参。
 *
 * 编码参数 / 播放环深度刻意**不暴露**：M1 冻结为 engine 的默认值（20 ms / 160 kbps / VBR / 48 kHz），
 * 开成旋钮只会让「零重采样」与延迟预算失去唯一解。
 */
data class EngineStartConfig (
    /**
     * 用户可见节点名（仅展示，不参与身份判定）。
     */
    var `nodeName`: kotlin.String, 
    /**
     * 身份材料（`cert.pem` / `key.pem`）与信任库（`trust.json`）的落地目录。
     */
    var `dataDir`: kotlin.String, 
    /**
     * QUIC 监听端口；`0` = 默认 `58290`。
     */
    var `listenPort`: kotlin.UShort, 
    /**
     * **平台侧额外声明**的能力位（§13 的协商位图，位名与语义见 `audiolink_types::Capabilities`）。
     *
     * 语义是「**这台设备能**做什么」，**不是**「此刻正在用什么」—— 与 `CAPTURE` / `PLAYOUT` 同口径
     * （纯接收端「不需要」CAPTURE，但它并不是「不能」采集）。所以发送源关着也照旧声明：
     * 对端据此知道「这台设备具备内录 / 麦克风」，真正用不用得上由后续的授权流程与用户选择决定。
     *
     * `0`（缺省）＝ 与加上这个字段之前**逐位一致**，也就是内核默认的 `Capabilities::CURRENT`；
     * 非零值与内核默认取**并集**，因此**不可能**抹掉必需位（`REQUIRED` 只有 `OPUS`）——
     * 若允许调用方覆盖整张位图，一个只写 `MICROPHONE` 的调用方就会让双方缺必需位、直接拒连。
     */
    var `capabilities`: kotlin.UInt = 0u
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEngineStartConfig: FfiConverterRustBuffer<EngineStartConfig> {
    override fun read(buf: ByteBuffer): EngineStartConfig {
        return EngineStartConfig(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: EngineStartConfig) = (
            FfiConverterString.allocationSize(value.`nodeName`) +
            FfiConverterString.allocationSize(value.`dataDir`) +
            FfiConverterUShort.allocationSize(value.`listenPort`) +
            FfiConverterUInt.allocationSize(value.`capabilities`)
    )

    override fun write(value: EngineStartConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`nodeName`, buf)
            FfiConverterString.write(value.`dataDir`, buf)
            FfiConverterUShort.write(value.`listenPort`, buf)
            FfiConverterUInt.write(value.`capabilities`, buf)
    }
}



/**
 * 本机状态（`localStatus()`）。
 */
data class LocalStatus (
    /**
     * 指纹短码（16 hex 字符）—— UI 展示用。
     */
    var `idShort`: kotlin.String, 
    /**
     * 完整指纹（64 hex 字符）—— 信任判定的唯一依据。
     */
    var `idHex`: kotlin.String, 
    /**
     * 节点展示名。
     */
    var `name`: kotlin.String, 
    /**
     * 实际监听的 `ip:port`。
     */
    var `addr`: kotlin.String, 
    /**
     * `win` / `android` / `unknown`。
     */
    var `platform`: kotlin.String, 
    /**
     * 能力位原始值。
     */
    var `capsBits`: kotlin.UShort, 
    /**
     * 本机能否推流（= 配了采集回调）。
     */
    var `canSend`: kotlin.Boolean, 
    /**
     * 本机能否接收（= 配了播放回调）。
     */
    var `canReceive`: kotlin.Boolean, 
    /**
     * 协议版本（`0x0201`）。
     */
    var `protoVersion`: kotlin.UShort
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLocalStatus: FfiConverterRustBuffer<LocalStatus> {
    override fun read(buf: ByteBuffer): LocalStatus {
        return LocalStatus(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterUShort.read(buf),
        )
    }

    override fun allocationSize(value: LocalStatus) = (
            FfiConverterString.allocationSize(value.`idShort`) +
            FfiConverterString.allocationSize(value.`idHex`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`addr`) +
            FfiConverterString.allocationSize(value.`platform`) +
            FfiConverterUShort.allocationSize(value.`capsBits`) +
            FfiConverterBoolean.allocationSize(value.`canSend`) +
            FfiConverterBoolean.allocationSize(value.`canReceive`) +
            FfiConverterUShort.allocationSize(value.`protoVersion`)
    )

    override fun write(value: LocalStatus, buf: ByteBuffer) {
            FfiConverterString.write(value.`idShort`, buf)
            FfiConverterString.write(value.`idHex`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`addr`, buf)
            FfiConverterString.write(value.`platform`, buf)
            FfiConverterUShort.write(value.`capsBits`, buf)
            FfiConverterBoolean.write(value.`canSend`, buf)
            FfiConverterBoolean.write(value.`canReceive`, buf)
            FfiConverterUShort.write(value.`protoVersion`, buf)
    }
}



/**
 * 一个对端的快照。
 */
data class PeerView (
    /**
     * 指纹短码。
     */
    var `idShort`: kotlin.String, 
    /**
     * 完整指纹。
     */
    var `idHex`: kotlin.String, 
    /**
     * 对端展示名（对端自报，**不参与信任判定**）。
     */
    var `name`: kotlin.String, 
    /**
     * 对端地址 `ip:port`。
     */
    var `addr`: kotlin.String, 
    /**
     * `idle` / `handshaking` / `streaming` / `degraded` / `reconnecting` / `failed`
     * （与桌面端契约 §6 的 `state` 字面量同一套）。
     */
    var `state`: kotlin.String, 
    /**
     * 是否已在信任库中。
     */
    var `trusted`: kotlin.Boolean, 
    /**
     * 该对端的遥测快照（`peers` 字段恒为 1）。
     */
    var `telemetry`: TelemetryView
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePeerView: FfiConverterRustBuffer<PeerView> {
    override fun read(buf: ByteBuffer): PeerView {
        return PeerView(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterTypeTelemetryView.read(buf),
        )
    }

    override fun allocationSize(value: PeerView) = (
            FfiConverterString.allocationSize(value.`idShort`) +
            FfiConverterString.allocationSize(value.`idHex`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`addr`) +
            FfiConverterString.allocationSize(value.`state`) +
            FfiConverterBoolean.allocationSize(value.`trusted`) +
            FfiConverterTypeTelemetryView.allocationSize(value.`telemetry`)
    )

    override fun write(value: PeerView, buf: ByteBuffer) {
            FfiConverterString.write(value.`idShort`, buf)
            FfiConverterString.write(value.`idHex`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`addr`, buf)
            FfiConverterString.write(value.`state`, buf)
            FfiConverterBoolean.write(value.`trusted`, buf)
            FfiConverterTypeTelemetryView.write(value.`telemetry`, buf)
    }
}



/**
 * 遥测快照（`telemetry()`；字段尽可能对齐桌面契约 §6 的 `TelemetryView`）。
 */
data class TelemetryView (
    /**
     * 这份快照覆盖的对端数（`telemetry()` 是全部，`PeerView.telemetry` 恒为 1）。
     */
    var `peers`: kotlin.UInt, 
    /**
     * 流 ID（未推流时为 0）。
     */
    var `streamId`: kotlin.UInt, 
    /**
     * QUIC 平滑 RTT（µs）。
     */
    var `rttUs`: kotlin.UInt, 
    /**
     * 到达间隔抖动 P50（µs）。
     */
    var `jitterUs`: kotlin.UInt, 
    /**
     * 到达间隔抖动 P95（µs）。
     */
    var `jitterP95Us`: kotlin.UInt, 
    /**
     * 丢包率（百分比，`0.0`–`100.0`）。
     */
    var `lossPct`: kotlin.Double, 
    /**
     * 实际编码码率（bps）。
     */
    var `bitrateBps`: kotlin.UInt, 
    /**
     * 帧长（ms）。
     */
    var `frameMs`: kotlin.UByte, 
    /**
     * 声道数。
     */
    var `channels`: kotlin.UByte, 
    /**
     * 播放环水位（µs）。
     */
    var `bufferLevelUs`: kotlin.UInt, 
    /**
     * 累计欠载次数。
     */
    var `underruns`: kotlin.UInt, 
    /**
     * 丢包隐藏次数（M1 只计数，不做掩盖）。
     */
    var `plcCount`: kotlin.UInt, 
    /**
     * 迟到丢弃包数。
     */
    var `lateDrops`: kotlin.UInt, 
    /**
     * 估算端到端延迟（µs）。
     */
    var `e2eLatencyUs`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTelemetryView: FfiConverterRustBuffer<TelemetryView> {
    override fun read(buf: ByteBuffer): TelemetryView {
        return TelemetryView(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: TelemetryView) = (
            FfiConverterUInt.allocationSize(value.`peers`) +
            FfiConverterUInt.allocationSize(value.`streamId`) +
            FfiConverterUInt.allocationSize(value.`rttUs`) +
            FfiConverterUInt.allocationSize(value.`jitterUs`) +
            FfiConverterUInt.allocationSize(value.`jitterP95Us`) +
            FfiConverterDouble.allocationSize(value.`lossPct`) +
            FfiConverterUInt.allocationSize(value.`bitrateBps`) +
            FfiConverterUByte.allocationSize(value.`frameMs`) +
            FfiConverterUByte.allocationSize(value.`channels`) +
            FfiConverterUInt.allocationSize(value.`bufferLevelUs`) +
            FfiConverterUInt.allocationSize(value.`underruns`) +
            FfiConverterUInt.allocationSize(value.`plcCount`) +
            FfiConverterUInt.allocationSize(value.`lateDrops`) +
            FfiConverterUInt.allocationSize(value.`e2eLatencyUs`)
    )

    override fun write(value: TelemetryView, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`peers`, buf)
            FfiConverterUInt.write(value.`streamId`, buf)
            FfiConverterUInt.write(value.`rttUs`, buf)
            FfiConverterUInt.write(value.`jitterUs`, buf)
            FfiConverterUInt.write(value.`jitterP95Us`, buf)
            FfiConverterDouble.write(value.`lossPct`, buf)
            FfiConverterUInt.write(value.`bitrateBps`, buf)
            FfiConverterUByte.write(value.`frameMs`, buf)
            FfiConverterUByte.write(value.`channels`, buf)
            FfiConverterUInt.write(value.`bufferLevelUs`, buf)
            FfiConverterUInt.write(value.`underruns`, buf)
            FfiConverterUInt.write(value.`plcCount`, buf)
            FfiConverterUInt.write(value.`lateDrops`, buf)
            FfiConverterUInt.write(value.`e2eLatencyUs`, buf)
    }
}





/**
 * FFI 失败。
 *
 * 用 `enum` 而不是 struct：UniFFI 0.29 的 `#[derive(uniffi::Error)]` 只支持枚举
 * （`uniffi_macros::error::expand_error` 内部构造的是 `EnumItem`）。
 * 只有一个变体 `Failure`；Kotlin 侧生成的是 `FfiException.Failure(code, messageText, context)`
 * —— 类型名带 `Exception` 后缀是 UniFFI 的 Kotlin 命名规则。
 *
 * # 为什么字段是 `message_text` 而不是 `message`
 *
 * Kotlin 生成的 `Failure` 继承 `FfiException`，而它继承 `kotlin.Exception` → `Throwable`；
 * UniFFI 同时会给异常生成一个 `override val message` getter，那个 getter 又要引用记录里的同名字段
 * —— 同名冲突，实测编译器报：
 *
 * ```text
 * e: 'message' hides member of supertype 'Throwable' and needs an 'override' modifier
 * e: Conflicting declarations: val message: String
 * ```
 *
 * 所以字段改名为 `message_text`（Kotlin 侧自动转成 `messageText`）。**语义不变**：
 * 契约 §1 里那一格还是「§11 错误码短名」（如 `NOT_PAIRED`），
 * 完整人话串由 `Throwable.message` 给出（`1002 NOT_PAIRED: peer requires pin pairing`）。
 */
sealed class FfiException: kotlin.Exception() {
    
    /**
     * 统一失败形态。
     *
     * - `code`：`docs/03-protocol.md` §11 错误码的数值形式（如 `1002` = `NOT_PAIRED`）；
     * - `message_text`：错误码短名（如 `NOT_PAIRED`），供日志 / UI 查找与展示；
     * - `context`：出错细节（谁、在哪、什么值）。
     */
    class Failure(
        
        /**
         * §11 错误码数值。
         */
        val `code`: kotlin.UShort, 
        
        /**
         * §11 错误码短名。
         */
        val `messageText`: kotlin.String, 
        
        /**
         * 失败细节。
         */
        val `context`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "code=${ `code` }, messageText=${ `messageText` }, context=${ `context` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<FfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): FfiException = FfiConverterTypeFfiError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiError : FfiConverterRustBuffer<FfiException> {
    override fun read(buf: ByteBuffer): FfiException {
        

        return when(buf.getInt()) {
            1 -> FfiException.Failure(
                FfiConverterUShort.read(buf),
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FfiException): ULong {
        return when(value) {
            is FfiException.Failure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUShort.allocationSize(value.`code`)
                + FfiConverterString.allocationSize(value.`messageText`)
                + FfiConverterString.allocationSize(value.`context`)
            )
        }
    }

    override fun write(value: FfiException, buf: ByteBuffer) {
        when(value) {
            is FfiException.Failure -> {
                buf.putInt(1)
                FfiConverterUShort.write(value.`code`, buf)
                FfiConverterString.write(value.`messageText`, buf)
                FfiConverterString.write(value.`context`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





/**
 * Kotlin 实现的 PCM 灌入口（`AudioLinkService.feedPcm` 就是它）。
 *
 * 契约（Kotlin 侧必须遵守，否则声音会错位）：
 * 1. `samples` 是 **48 kHz / f32 / 2ch 交错**样本，长度恒为 `frames * 2`；
 * 2. **从任意线程调用**：内核的播放线程是 Rust 线程（`audiolink-playout`，不是 UI 线程、也不是
 * Kotlin 的主线程），实现必须线程安全（落到 `PcmRingBuffer` 上时要自己加锁）；
 * 3. 返回值 = 实际接收的帧数，仅供诊断；`< frames` 表示 Kotlin 侧环满。
 */
public interface PcmFeed {
    
    /**
     * 交付一段 PCM。
     */
    fun `feedPcm`(`samples`: List<kotlin.Float>, `frames`: kotlin.Int): kotlin.Int
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfacePcmFeed {
    internal object `feedPcm`: UniffiCallbackInterfacePcmFeedMethod0 {
        override fun callback(`uniffiHandle`: Long,`samples`: RustBuffer.ByValue,`frames`: Int,`uniffiOutReturn`: IntByReference,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypePcmFeed.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`feedPcm`(
                    FfiConverterSequenceFloat.lift(`samples`),
                    FfiConverterInt.lift(`frames`),
                )
            }
            val writeReturn = { value: kotlin.Int -> uniffiOutReturn.setValue(FfiConverterInt.lower(value)) }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypePcmFeed.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfacePcmFeed.UniffiByValue(
        `feedPcm`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_audiolink_ffi_fn_init_callback_vtable_pcmfeed(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypePcmFeed: FfiConverterCallbackInterface<PcmFeed>()





/**
 * Kotlin 实现的 PCM 拉取口（发送方向用，M1 Android 不用）。
 *
 * 契约：
 * 1. 返回 48 kHz / f32 / 2ch 交错样本，长度 **偶数**、且 ≤ `max_samples`；
 * 2. 返回空 = 暂无数据（不要忙等返回 0，那会在采集线程里变成热循环）；
 * 3. 同样可能从 Rust 音频线程调用，实现必须线程安全。
 */
public interface PcmPull {
    
    /**
     * 取最多 `max_samples` 个交错样本。
     */
    fun `readPcm`(`maxSamples`: kotlin.Int): List<kotlin.Float>
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfacePcmPull {
    internal object `readPcm`: UniffiCallbackInterfacePcmPullMethod0 {
        override fun callback(`uniffiHandle`: Long,`maxSamples`: Int,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypePcmPull.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`readPcm`(
                    FfiConverterInt.lift(`maxSamples`),
                )
            }
            val writeReturn = { value: List<kotlin.Float> -> uniffiOutReturn.setValue(FfiConverterSequenceFloat.lower(value)) }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypePcmPull.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfacePcmPull.UniffiByValue(
        `readPcm`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_audiolink_ffi_fn_init_callback_vtable_pcmpull(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypePcmPull: FfiConverterCallbackInterface<PcmPull>()




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypePcmFeed: FfiConverterRustBuffer<PcmFeed?> {
    override fun read(buf: ByteBuffer): PcmFeed? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePcmFeed.read(buf)
    }

    override fun allocationSize(value: PcmFeed?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypePcmFeed.allocationSize(value)
        }
    }

    override fun write(value: PcmFeed?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePcmFeed.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypePcmPull: FfiConverterRustBuffer<PcmPull?> {
    override fun read(buf: ByteBuffer): PcmPull? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePcmPull.read(buf)
    }

    override fun allocationSize(value: PcmPull?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypePcmPull.allocationSize(value)
        }
    }

    override fun write(value: PcmPull?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePcmPull.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceFloat: FfiConverterRustBuffer<List<kotlin.Float>> {
    override fun read(buf: ByteBuffer): List<kotlin.Float> {
        val len = buf.getInt()
        return List<kotlin.Float>(len) {
            FfiConverterFloat.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Float>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterFloat.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Float>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterFloat.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePeerView: FfiConverterRustBuffer<List<PeerView>> {
    override fun read(buf: ByteBuffer): List<PeerView> {
        val len = buf.getInt()
        return List<PeerView>(len) {
            FfiConverterTypePeerView.read(buf)
        }
    }

    override fun allocationSize(value: List<PeerView>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePeerView.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PeerView>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePeerView.write(it, buf)
        }
    }
}








        /**
         * 主动连接对端（FR-17 手工 IP）。成功返回对端快照。
         *
         * 对端要求 PIN 配对时返回 `1002 NOT_PAIRED`，但**这不是连接失败**：QUIC 握手与会话已经在，
         * UI 提示用户输入 PIN 后调用 [`submit_pin`] 即可继续同一条连接（见 engine `connect()` 的文档）。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `connect`(`addr`: kotlin.String) : PeerView {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_connect(FfiConverterString.lower(`addr`),),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_rust_buffer(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_rust_buffer(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_rust_buffer(future) },
        // lift function
        { FfiConverterTypePeerView.lift(it) },
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 本机（接收端）当前展示给用户的配对 PIN；没有在配对时返回 `None`。
         */
    @Throws(FfiException::class) fun `displayedPin`(): kotlin.String? {
            return FfiConverterOptionalString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_displayed_pin(
        _status)
}
    )
    }
    

        /**
         * 启动引擎并开始监听入站连接。
         *
         * - `playout`：接收方向的内核 PCM 出口（Android 传 `AudioLinkService`）；`null` = 本机不接收；
         * - `capture`：发送方向的 PCM 入口；`null` = 本机不推流（M1 Android 即为 `null`）；
         * - 两个回调都传 `null` 时能力位为 0，UI 可以据此置灰按钮（能力位只由「有没有工厂」决定）。
         *
         * 幂等：同一份 `config` 重复调用返回当前状态（Android 前台服务会被系统反复拉起，
         * 调用方的真实意图是「确保在跑」）；配置不同则返回 `1009 BUSY`，不做静默替换。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `engineStart`(`config`: EngineStartConfig, `playout`: PcmFeed?, `capture`: PcmPull?) : LocalStatus {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_engine_start(FfiConverterTypeEngineStartConfig.lower(`config`),FfiConverterOptionalTypePcmFeed.lower(`playout`),FfiConverterOptionalTypePcmPull.lower(`capture`),),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_rust_buffer(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_rust_buffer(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_rust_buffer(future) },
        // lift function
        { FfiConverterTypeLocalStatus.lift(it) },
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 停止引擎（幂等）。未启动时返回 `Ok`：调用方的意图是「确保停下来」。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `engineStop`() {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_engine_stop(),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_void(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_void(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_void(future) },
        // lift function
        { Unit },
        
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 本机状态。
         */
    @Throws(FfiException::class) fun `localStatus`(): LocalStatus {
            return FfiConverterTypeLocalStatus.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_local_status(
        _status)
}
    )
    }
    

        /**
         * 已连接对端列表。
         */
    @Throws(FfiException::class) fun `peers`(): List<PeerView> {
            return FfiConverterSequenceTypePeerView.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_peers(
        _status)
}
    )
    }
    

        /**
         * 契约 §8 的 `protocolSelfTest() -> String`。
         */ fun `protocolSelfTest`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_protocol_self_test(
        _status)
}
    )
    }
    

        /**
         * 开始向当前对端推流（发送方向）。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `startSend`() {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_start_send(),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_void(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_void(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_void(future) },
        // lift function
        { Unit },
        
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 停止推流（保留连接与信任）。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `stopSend`() {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_stop_send(),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_void(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_void(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_void(future) },
        // lift function
        { Unit },
        
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 提交对端屏幕上显示的 6 位 PIN（本机是发起端时用）。
         */
    @Throws(FfiException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
     suspend fun `submitPin`(`pin`: kotlin.String) {
        return uniffiRustCallAsync(
        UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_submit_pin(FfiConverterString.lower(`pin`),),
        { future, callback, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_poll_void(future, callback, continuation) },
        { future, continuation -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_complete_void(future, continuation) },
        { future -> UniffiLib.INSTANCE.ffi_audiolink_ffi_rust_future_free_void(future) },
        // lift function
        { Unit },
        
        // Error FFI converter
        FfiException.ErrorHandler,
    )
    }

        /**
         * 遥测快照：当前对端的指标 + 对端总数。
         */
    @Throws(FfiException::class) fun `telemetry`(): TelemetryView {
            return FfiConverterTypeTelemetryView.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_audiolink_ffi_fn_func_telemetry(
        _status)
}
    )
    }
    


